packages/mixer/src/components/Withdraw/Withdraw.tsx
packages/ui-components/src/Inputs/InputLabel/InputLabel.tsx
packages/ui-components/src/Inputs/InputSection/InputSection.tsx
packages/ui-components/src/Inputs/MixerGroupSelect/MixerGroupSelect.tsx
packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
packages/ui-components/src/Inputs/WalletTokenInput/WalletTokenInput.tsx
packages/ui-components/src/styling/themes/overides/light-theme-overrides.ts

* Split out container display from the `InputLabel` component into an `InputSection` component. This was necessary for the 'Token for Deposit' label.
* Typography overrides for variants used in the AccountManager display.

QA: Fix homepage with chain issues

---

packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
packages/react-environment/src/api-providers/polkadot/polkadot-transaction.ts
packages/react-environment/src/api-providers/web3/web3-mixer-deposit.ts
packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
packages/ui-components/src/notification/DepositNotification.tsx
packages/ui-components/src/notification/Notification.tsx
packages/wallet/src/providers/polkadot/transaction-notification-config.tsx

* Implement style fixes for some fonts on Deposit modal.
* Change to a more descriptive Deposit Notification.
Before:
After:
Notification:

QA: Deposit modal fixes

---

packages/apps/src/configs/evm/SupportedMixers.ts
packages/react-environment/src/WebbProvider.tsx
packages/react-environment/src/error/interactive-errors/evm-network-conflict.ts

These changes remove dependency on activeChain variable when initializing interactive feedback in the app.  This allows for an unsupported network error on page load.
It is a bit awkward though because the error will show the Ethereum Mainnet as something 'unknown'. Maybe it would be better to move forward with an update to WebbErrors to differentiate between 'UnknownChain' and 'UnsupportedChain'?

Throw an unsupported network error if the chain is not recognized

---

packages/contracts/src/contracts/tornado-anchor.ts
packages/mixer/src/hooks/withdraw/useWithdraw.tsx
packages/react-environment/src/WebbProvider.tsx
packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
packages/react-environment/src/error/interactive-errors/misbehaving-relayer.tsx
packages/utils/src/webb-error/webb-error.class.ts

This PR allows for communication with the relayer to store the fetched leaves if the following conditions are met:
1. The merkle root computed from the leaves query matches a known root on chain.
2. The reported block from the relayer contains the transaction of the last entry in the leaves.
These validations are necessary to prevent malicious relayers from injecting incorrect state into the local storage of the client. These validations could allow a client to withdraw without a relayer but quickly build proofs - if we wish to implement this functionality.
Additionally, this PR detects relayers which are not operating properly and shows an interactiveFeedback modal.

Retrieve leaves from relayer and store if appropriate

---

packages/apps/src/configs/evm/SupportedMixers.ts
packages/apps/src/configs/wallets/wallets-config.ts
packages/bridge/src/components/Withdraw/Withdraw.tsx
packages/mixer/src/components/Withdraw/Withdraw.tsx
packages/react-environment/src/api-providers/web3/web3-bridge-withdraw.ts
packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
packages/react-environment/src/api-providers/web3/webb-web3-provider.ts
packages/react-environment/src/webb-context/bridge/bridge-config.ts
packages/react-environment/src/webb-context/relayer/webb-relayer.class.ts
packages/ui-components/src/NetworkManger/NetworkManager.tsx

This PR changes the 'switch chain' functionality. It enforces the user to switch chains before withdrawing. This is because there were issues with the correct WebbProvider state with the previous switch chain strategy in withdraw flows.
Relayers available for selection are dependent on the note rather than the selected chain. Relayers displayed must support event-watching.
Tornados are properly interacting with relayers; while Anchors have the appropriate relayers displayed, but cannot currently be selected.

Relay withdraw requests for Tornados and proper relayer display for Anchors

---

packages/apps/src/App.tsx
packages/bridge/src/Bridge.tsx
packages/bridge/src/components/Withdraw/Withdraw.tsx
packages/mixer/src/Mixer.tsx
packages/mixer/src/components/Withdraw/Withdraw.tsx
packages/page-transfer/src/index.tsx
packages/page-wrap-unwrap/src/index.tsx
packages/react-components/src/IPDisplay/IPDisplay.tsx
packages/react-components/src/PermissionedAccess/DisableAdblock.tsx
packages/react-components/src/PermissionedAccess/PermissionedAccess.tsx
packages/react-components/src/Withdraw/WithdrawSuccessModal.tsx
packages/react-environment/src/IpProvider.tsx
packages/react-environment/src/index.ts
packages/react-hooks/src/useRelayerIp.ts

Update the implementation for retrieving for IP and related information. Previously it was a hook which would be called separately in each included component.  Now this information is retrieved in a react context which makes the call once and provides to the rest of the components.

Only make one call to ipapi for geolocation and use across the app

---

packages/bridge/src/hooks/deposit/useBridgeDeposit.tsx

If a user is selected on the Bridge deposit screen and switches chains in metamask to another chain (which is supported on tornados but not in the bridge), then the values populated in the bridge deposit will stay as if it were still selected on the old chain.
In the useEffect cleanup on depositApi change, set the active bridge state to null. This will remove the destination chain selection values and reset the selected token.

Set bridge state to null in depositApi useEffect cleanup

---

packages/page-wrap-unwrap/src/hooks/useWrapUnwrap.ts
packages/page-wrap-unwrap/src/index.tsx

If the user has not selected a wallet or approved in metamask and visits the wrap/unwrap page, the website will crash. This is because setState call in functions setRightHandToken and setLeftHandToken in useWrapUnwrap hook is re-evaluated on render in the page-wrap-unwrap - which imports the hook.
The website doesn't crash. Do not update UI when functions change.

Fix infinite render state on wrap/unwrap without selected network

---

packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts

The latest relayer stores the reward address in a property called beneficiary while old relayers store this address in a property called account. Relay transactions sent from the dapp -> a relayer will fail because they are generated without the proper reward address.
properly take into account the 'beneficiary' field if the account field is absent.

Add beneficiary relayer properties for tornado relayer transaction

---

packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
packages/utils/src/misc/app-mode.ts

`development.webb.tools` attempts to use cached fixtures instead of fetching from IPFS.
any deployed build will fetch from IPFS instead of cached fixtures.

Fix development.webb.tools to use IPFS fixtures instead of cached ones

---

packages/apps/src/initI18n.ts
packages/react-environment/src/WebbProvider.tsx
packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
packages/react-environment/src/api-providers/polkadot/polkadot-transaction.ts
packages/react-environment/src/api-providers/polkadot/webb-polkadot-provider.ts
packages/react-environment/src/api-providers/web3/web3-bridge-deposit.ts
packages/react-environment/src/api-providers/web3/web3-bridge-withdraw.ts
packages/react-environment/src/api-providers/web3/web3-mixer-deposit.ts
packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
packages/react-environment/src/api-providers/web3/web3-wrap-unwrap.ts
packages/react-environment/src/api-providers/web3/webb-web3-provider.ts
packages/react-environment/src/webb-context/webb-provider.interface.ts
packages/wallet/src/providers/polkadot/polkadot-provider.ts
packages/wallet/src/providers/polkadot/transaction-notification-config.tsx

`NotificaitonApi` and `TransactionConfig` are used across the providers
Issue Number: Closes #331 
```
// Function call to register a notification
export type NotificationHandler = ((notification: NotificationPayload) => string | number) & {
// remove the notification programmatically
remove(key: string | number): void;
}
```
Added this interface to the provider will make it easer to control the behavior of ht notification

[RE] Linking the notification API/TX notification config to the provider

---

packages/api-providers/src/web3/webb-provider.ts
packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
packages/react-environment/src/WebbProvider.tsx
packages/react-hooks/src/currency/useNativeCurrencyBalance.tsx

- fix: change the order of function call for removing warning
- fix: not display address when changing account then make a hard refresh
- fix: sync display account with Metamask account when changing account using metamask
- Account did not display when you switch to another account and made a hard refresh on the Dapp (on the first render).
- The displayed account on the Dapp won't update properly when switching between different accounts using Metamask wallet.
Issue Number: Closes #409 
- Display the account correctly when you switch to another account and make a hard refresh.
- Added a missing event listener for `accountsChange` event to sync with Metamask account.
I added a video …

Fix sync the display account with metamask account

---

packages/api-providers/src/polkadot/anchor-api.ts

Bridge tokens for the substrate side are filtered for `Governable` and `ORML`
Issue Number: Closes #459 
Substrate tokens are now filtered based on the support provided by the config and type being  `OMRL` or `NATIVE`.

Fix substrate native token not showing

---

packages/api-providers/src/abstracts/anchor/vanchor-deposit.ts
packages/api-providers/src/web3/vanchor-deposit.ts
packages/react-components/src/Transact/TransactionProcessingModal.tsx
packages/vbridge/src/components/Deposit/Deposit.tsx

- fix: add missing set state in `cancel` function
- refactor: handle error when user cancel tx
- chore: improve the ui when user cancel tx
- fix: add missing terminal state to reset the state to ideal
- Fix the error after canceling a transaction the dApp would not be used
- Improve the UI when canceling a transaction
- Closes https://github.com/webb-tools/webb-dapp/issues/484
-----
https://user-images.githubusercontent.com/60747384/186150943-5d9c930a-4da3-4a29-9e29-24463140f30f.mp4

Fix provider not working after cancel a transaction

---

packages/apps/webpack.base.js
packages/webb-ui-components/src/components/Avatar/types.d.ts
packages/webb-ui-components/src/components/AvatarGroup/types.d.ts
packages/webb-ui-components/src/components/Button/Button.tsx
packages/webb-ui-components/src/components/Button/ButtonSpinner.tsx
packages/webb-ui-components/src/components/Button/index.ts
packages/webb-ui-components/src/components/Button/types.d.ts
packages/webb-ui-components/src/components/Button/utils.ts
packages/webb-ui-components/src/components/index.ts
packages/webb-ui-components/src/icons/Spinner.tsx
packages/webb-ui-components/src/icons/index.ts
packages/webb-ui-components/src/icons/types.d.ts
packages/webb-ui-components/src/types/index.d.ts
packages/webb-ui-components/src/typography/types.d.ts

- refactor: extract common props into `WebbComponentBase` interface
- chore: add `Spinner` icon for loading state
- feat: add new `Button` component
- fix: add missing config for `webpack` dev server
- setup new `Button` component
- Define base interface for all components
- Add missing config for `webpack` dev server.
- Closes https://github.com/webb-tools/webb-dapp/issues/508
-----
I cannot test the component with the current app. Because it conflicts with the existing style from Material-UI.
We need an isolated sandbox to test new components.

New Button Component

---

packages/page-statistics/src/generated/graphql.tsx
packages/page-statistics/src/gql/proposals.graphql
packages/page-statistics/src/gql/public-keys.graphql
packages/page-statistics/src/provider/hooks/useKeys.ts
packages/page-statistics/src/provider/hooks/useProposal.ts

- For Proposals and keys there is a new `next` `prev` ids to fetch the next item if any
- The `next` `prev` can be null which means there is no previous or next entry
- Closes #600 
-----

Include the previous and next  entity id for single view

---

packages/react-components/src/AppBar/ThemeSwitcher.tsx

- hide input from `ThemeSwitcher` component since a small square was visible (on firefox)
- None
-----
**before**
**after**

fix(ThemeSwitcher): input visibility

---

.graphqlconfig
codegen.yml
package.json
yarn.lock

- fix: storybook with mono repo
- add fonts inside css folder to fix building error
- feat: add graphql type generation to mono repo
- Add GraphQL Type Generation Script With Mono Repo
- Closes `NaN`
-----

Add GraphQL Type Generation Script With Mono Repo

---

apps/bridge-dapp/package.json
apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
apps/stats-dapp/package.json
libs/tailwind-preset/package.json
libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
libs/webb-ui-components/src/components/IconWithTooltip/index.ts
libs/webb-ui-components/src/components/IconWithTooltip/types.d.ts
libs/webb-ui-components/src/components/Table/TData.tsx
libs/webb-ui-components/src/components/Table/Table.tsx
libs/webb-ui-components/src/components/TokenPairIcons/TokenPairIcons.tsx
libs/webb-ui-components/src/components/index.ts
package.json
yarn.lock

- Adding _tooltips_ for the **chain column** on the **shielded assets** table and **spend note** table
- Adding _tooltips_ for the **composition column** on the **shielded asset** table and **spend note** table
- Adding _tooltips_ for the **action column** on the **shielded asset** table
- Adding _dropdown menu_ for the **action column** on the **spend note** table
- Upgrade to Tailwind v3.2.4 (latest version) to support nested group class names.
- Closes https://github.com/webb-tools/webb-dapp/issues/724
- Closes https://github.com/webb-tools/webb-dapp/issues/733
- Closes https://github.com/webb-tools/webb-dapp/issues/729
-----
https://user-images.githubusercontent.com/60747384/204585359-2274974e-fc0c-4e69-b8bb-926b1552bec1.mp4

Adding tooltips and dropdown for the note account table

---

apps/stats-dapp/src/provider/hooks/useAuthorities.ts

- Removes current and pending stats from upcoming thresholds table in authorities page.
- Closes #754

Removes current and pending stats from upcoming thresholds table

---

apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
libs/evm-contracts/src/webb-vanchor.ts

- Make the max button handler set the balance for the selected token (Wrappable asset for wrap & deposit,Governed asset for deposit)
- Added error message for the amount input
- disable the `Wrap and Deposit` or `Wrap` buttons for insufficient balances
- Closes #774 
https://user-images.githubusercontent.com/35463181/205900558-96b3e2a6-9871-40db-98f3-d296d5a81259.mp4
-----

Fix max balance and amount input error message

---

apps/stats-dapp/src/components/Header/Header.tsx
apps/stats-dapp/src/containers/Layout/Layout.tsx
apps/stats-dapp/src/provider/hooks/useKeys.ts
apps/stats-dapp/src/provider/stats-provider.tsx
libs/webb-ui-components/src/constants/index.ts

- Block explorer links changes based on custom data source endpoint and default endpoint.
- Bug fix: `RESET` in custom data source now resets the app's endpoint to it's default endpoint.
- Bug fix: `best` and `finalized` block chips now updates on custom data source endpoint but only works for `parachain` and `standalone` nodes.
- Closes #820 
- Closes #803 
- Closes #798

Dynamic block explorer link, RESET bug fix and best/finalized block chips updates on custom endpoint input

---

apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
apps/stats-dapp/src/provider/stats-provider.tsx
libs/webb-ui-components/src/hooks/useDarkMode.ts

- Updates `useDarkMode` hook to emit `localstorage` changes event such that we can listen to the event to get the current selected theme.
- Adds `isDarkMode` state to `statsContext` such that we can use `const { isDarkMode } = useStatsContext()` in any component to get the current selected theme.
- Updates `text`, `labels` and few `elements` colors of `Stacked Area Chart` to match the design with `light` and `dark` mode accordingly.
- Closes #618

Updates useDarkMode hook

---

apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
libs/webb-ui-components/src/components/BridgeInputs/RelayerInput.tsx

- Users can now deselect the selected active relayer.
https://user-images.githubusercontent.com/53374218/213903466-8f09e3ca-b8ef-4df2-928f-7bc166806e6a.mov
- Closes #839

Deselect active relayer

---

apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx

- Deposited asset balance is not shown as zero in token selection component while withdrawing.
https://user-images.githubusercontent.com/53374218/213958825-480524e0-7099-4f03-bc09-712705bf682c.mov
- Closes #889

Fixes withdraw asset token balance zero

---

apps/bridge-dapp/src/components/Header/Header.tsx

- Account and chain switcher component in the header does not disappear when switching between the chains.
https://user-images.githubusercontent.com/53374218/213812094-0aabaf5e-c037-4e40-b336-33f821ad7972.mov
- Closes #843

Fixes account component disappearing in header

---

libs/webb-ui-components/src/components/BridgeInputs/RecipientInput.tsx

- User is notified to change browser settings to allow clipboard access(if not already allowed) when `Paste` button is clicked to paste copied text from clipboard into recipient input in `Withdraw` and `Transfer` flow.
https://user-images.githubusercontent.com/53374218/214536574-45ac21e7-31af-46c5-806b-15b071d3b39e.mov
- Closes #845

Fixes clipboard paste error

---

libs/web3-api-provider/src/ext-provider/web3-provider.ts

- Removes `provider.enable()` and `provider.send()` methods while connecting to `Metamask` and replaces them with recommended method: `provider.request({ method: 'eth_requestAccounts' })`.
https://user-images.githubusercontent.com/53374218/215171646-014e4e8f-87f1-4f98-87b1-8064788719cf.mov
- Closes #747

Updates metamask deprecated methods usage

---

libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionCardFooter.tsx
libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx

- All failed transaction footer message nows shows `Transaction failed`.
- `Transaction failed` is now an external link to the explorer page.
- Updates transaction progress card text font sizes to match with the design.
https://user-images.githubusercontent.com/53374218/215603808-2b75b15f-3944-4704-950b-fc25fbdb6a36.mov
- Closes #932

Updates failed transaction message and transaction progress card font sizes

---

apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx

- Replaces action dropdown in available spend notes table with transfer button and withdraw button.
- Removes deposit button in shielded assets table.
- Closes #946 
- Closes #950 
https://user-images.githubusercontent.com/53374218/215881729-f8c894c0-00c7-42ec-ba02-f5026fe40c57.mov
-----

Replaces action dropdown and removes deposit button in table

---

apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx

- Updates `Note` to `Spend Note` with a title info in the spend available note table.
- Closes #944 (Only the last UI discrepancy is addressed in this PR, rest of them are addressed here: PR #963 )
-----

Updates spend notes table column header

---

apps/bridge-dapp/project.json
apps/bridge-dapp/webpack.base.js
apps/bridge-dapp/webpack.dev.js
apps/stats-dapp/webpack.config.js

- Update the configuration in `project.json` and webpack config files to support production build for `bridge-dapp` and `stats-dapp`
Build commands (in production):
- `bridge-dapp`: `yarn nx run bridge-dapp:build:production`
- `stats-dapp`: `yarn nx run stats-dapp:build:production`
- Closes `NaN`

Fixing Webpack Production Build

---

apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
libs/web3-api-provider/src/webb-provider.ts
libs/web3-api-provider/src/webb-provider/relayer-manager.ts
libs/web3-api-provider/src/webb-provider/vanchor-actions.ts

- Fixed the 32-byte consistent issues on the leaves and the roots return on-chain and returns from the relayer
- Passed missing React ref for removing error in the browser console
- Fixed resource Id not updating when switching to another chain because previously we got the `chainId` from object property instead of the provider so that the `chainId` won't update when we switch to another chain.
- Closes `NaN`
https://user-images.githubusercontent.com/60747384/222206592-ca6e61d3-fb6a-4d0c-a803-e0d31b910e9a.mp4

32-bytes Fixing for Leaves and Roots

---

apps/bridge-dapp/project.json
apps/bridge-dapp/webpack.base.js
apps/bridge-dapp/webpack.prod.js
apps/stats-dapp/project.json
apps/stats-dapp/webpack.config.js

- Removes console logs from `bridge` and `stats` dApp using `Terser` webpack plugin.
- Closes #797 
https://user-images.githubusercontent.com/53374218/223024505-482fd57f-ce0d-4d59-ba0f-3e9606e77ef0.mp4
-----

Adds Terser Webpack plugin to drop console in production

---

apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
libs/webb-ui-components/src/components/ListCard/types.ts

- Chain in `ChainListCard` will show `connected` chip if connected, `connecting` if in connecting state and `select` if current connected chain is not equal to the chain and if not in connecting state.
- Closes #877 
https://user-images.githubusercontent.com/53374218/224862201-7e2ce0fa-2ee2-4ee3-9ef8-878464050967.mov
-----

Adds connecting chip in ChainListCard component

---

apps/webbsite/src/components/BlogCard.tsx
apps/webbsite/src/components/sections/FeaturedPostSection.tsx

- Adds `Read` button to featured post blog card
- Updates featured post blog card to match with the design
- Adds transition on hover to blog card cover
https://user-images.githubusercontent.com/53374218/225595708-f78654a6-1fa5-4bc6-adaa-c1570ba4e173.mov

Updates featured post blog card

---

libs/dapp-config/src/relayer-config.ts
libs/relayer-manager-factory/src/relayer-manager-factory.ts

This PR removes relayers 4 and 5. The removed relayers will be used solely for development testing of changes and features (e.g. #1049 and / or #1048) whereas, relayers 1 - 3 will be used in production and will not be disrupted until changes land on `prod` environment. This based on the discussion between the dapp team and relayer team @shekohex @salman01zp @devpavan04  @AtelyPham. More details can be read [here](https://www.notion.so/hicommonwealth/Relayer-dApp-Support-ae4f0cd5f43d48579d95dd6f74c4a225).
- Closes 
-----
_Please be sure to add .stories documentation if any additions are made to …

Filter Relayers by the Environment

---

apps/stats-dapp/src/pages/Authorities.tsx

Updates `Authorities` page network threshold component to show `current` key details.
`Keys Overview`
`Authorities Overview`
-----

Fixes current key progress bar in authorities page

---

apps/stats-dapp/CHANGELOG.md
apps/stats-dapp/package.json
apps/stats-dapp/src/provider/hooks/useAuthorities.ts

- Fixes authorities table in authorities page. Authorities table now displays authority set of session zero.
- Closes #1122

[RELEASE]: Fixes authorities table in authorities page

---

apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx

- Quick action buttons in notes table now prompts a chain switch.
- Closes #1012 
https://user-images.githubusercontent.com/53374218/234685231-81cc3c5f-3b52-428e-a1ba-65d390517f5e.mov
https://user-images.githubusercontent.com/53374218/234688499-30ed089d-6f35-4551-ad8a-244fe202a315.mov

Quick action prompts a chain switch

---

.github/workflows/release.yml
apps/faucet/CHANGELOG.md
apps/faucet/package.json
apps/tangle-website/CHANGELOG.md
apps/tangle-website/package.json
apps/webbsite/CHANGELOG.md
apps/webbsite/package.json

- Setups release flow for facuet, webbsite, and tangle website
- Closes 
-----

[CHORE] Setups release flow for faucet, webbsite, and tangle website

---

apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx

- Graph's y-axis title is now displayed horizontally.
- Updates graph's title from Proposal Overtime to Proposal (Submission) History

Stats Proposal Graph UI Fixes

---

apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
libs/web3-api-provider/src/webb-provider/vanchor-actions.ts

- Fix: fee should be `0` when no relayer is selected, so the contract won't transfer the fee to `zeroAddress`.
- Renaming variables in the transfer file for more clarity.
- Closes https://github.com/webb-tools/webb-dapp/issues/1194

Hot Fixes #2 for the Bridge

---

.github/workflows/deploy-bridge-dapp-dev.yml
.github/workflows/deploy-stats-dapp-dev.yml
apps/bridge-dapp/project.json
apps/bridge-dapp/webpack.base.js
apps/stats-dapp/webpack.config.js
nx.json
yarn.lock

- This PR is unifying the build directories to root `dist` for all apps.
- We need to update the CI of the `bridge-dapp` and `stats-dapp` points to `dist/apps/bridge-dapp` and  `dist/apps/bridge-dapp` for app build directories.

Unifying `dist` Dirs for all Apps

---

apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
apps/stats-dapp/src/utils/getProposalsData.ts

- Adds a check for proposal data on proposal detail page to prevent from crashing. This crash is caused as a result of indexing of unknown proposals fix in this [PR](https://github.com/webb-tools/webb-graphql/pull/85) on webb-graphql.
- Currently, when a proposal is added (created later, meaning, created not as a result of `DKGProposalHandlerSection.ProposalAdded` event but created when proposal gets removed i.e as a result of `DKGProposalHandlerSection.ProposalRemoved` event), the event data is missing which causes the crash on stats dapp.
- To prevent this, stats dapp now displays `{expired: true}` in proposal details page when the data is not present and was removed, just like in the tangle event logs shown below.
NOTE: We should further investigate and add a fix to display the missing …

Adds a check for proposal data on proposal detail page to prevent from crashing

---

apps/stats-dapp/src/provider/hooks/useProposals.ts

- Updates `useProposals` and `useProposal` hooks to make a graphql query with the fetch policy of `network-only` and with a polling interval of ten seconds to make sure we always see the proposal data as they happen in real-time.

Updates proposals query's fetch policy to always fetch latest data

---

apps/tangle-website/src/components/sections/FAQSection.tsx

- Make Accordion Item in FAQ Section collapsible
- Make it easier for users to open an item by making adjusting the padding of AccordionButton
- Remove the default open item to make the UI more clear for the users
- Closes #1305 
https://github.com/webb-tools/webb-dapp/assets/69841784/6fa622ae-02d3-4a16-83a9-0a9bb4d49072
-----

Make accordion item in FAQ easier to open and collapsible

---

libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx

-  Replace the term Bridging Token with Shielded Pool on the bridge card for deposit, transfer, and withdrawal flow to improve the understanding of their shielded assets.
- Adds tooltip for Shielded Pool.
- Update search box copy to 'Search pool or enter contract address'.
- Removes unavailable token display (as shown below: AGOR, WETH etc.) from token list.
- Removes the section on 'Don't see your asset? Try another account or wallet' 
Closes #1197

UI updates for improved transaction flow on bridge

---

apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
apps/bridge-dapp/src/components/Header/Header.tsx
apps/bridge-dapp/src/pages/PageBridge.tsx
apps/bridge-dapp/tailwind.config.js

At the 480px breakpoint, the layout switches to a one-column layout displaying only the bridge control card.
- Closes #1085 
-----

Add breakpoint 480px to show one column layout

---

apps/bridge-dapp/src/components/Header/Header.tsx
libs/webb-ui-components/src/components/NavigationMenu/NavigationMenuContent.tsx
libs/webb-ui-components/src/components/NavigationMenu/types.ts

Add the Faucet url in navigation menu in the Bridge site
- Closes #1297 
https://github.com/webb-tools/webb-dapp/assets/69841784/7a1f5db7-5351-4061-9ed3-6454525d6d07
-----

Add Faucet link in navigation menu

---

apps/stats-dapp/src/containers/Layout/Layout.tsx

- Adds fixed height for the layout component in stats dapp to have same background image orientation across different tabs. 
- Closes #1295 
https://github.com/webb-tools/webb-dapp/assets/53374218/52e7d55c-8111-47d2-833f-168d38818212

Fixes inconsistent stats background image

---

apps/bridge-dapp/CHANGELOG.md
apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
libs/abstract-api-provider/src/relayer/webb-relayer.ts
libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx

- Update the external URL of the relayer to the info URL
- Disable the radio button on the ChainListCard when no chains to select
- Closes https://github.com/webb-tools/webb-dapp/issues/1363
- Closes https://github.com/webb-tools/webb-dapp/issues/1379

[RELEASE] Relayer URL and Disable Radio When No Chains To Select

---

apps/tangle-website/src/pages/_document.tsx
apps/webbsite/src/pages/_document.tsx

As discussed with @monaiuu, we will set the font `Satoshi` to the marketing sites due to the fact that the font `Satoshi-Variable` is not well-supported on ios devices
- Closes #1281 
-----

Change to font Satoshi for marketing sites

---

apps/hubble-stats/netlify.toml

- Adding the missing Netlify config file for the `hubble-stats` app.

Adding missing hubble-stats netlify config

---

libs/web3-api-provider/src/VAnchor.ts
libs/web3-api-provider/src/webb-provider/vanchor-actions.ts

- Fix the token approval issue on the wrap and deposit process
- Closes https://github.com/webb-tools/webb-dapp/issues/1472
https://github.com/webb-tools/webb-dapp/assets/60747384/282fdc1e-99a6-4e58-a672-590a5281c1eb

Fix Token Approval Issue

---

libs/api-provider-environment/src/WebbProvider.tsx
libs/dapp-config/src/chains/evm/index.tsx
libs/web3-api-provider/src/utils/getViemClient.ts

- Add more RPC URLs to support multiple providers
- Fix the network storage by moving the `networkSwitched` event to be emitted outside of the if condition
- Fix default Polygon Mumbai RPC URL from `wagmi/references` library is inactive -> Override the an active RPC
- Add multiple provider support for `getViemClient` function.

Add More Rpc Urls to Support Multiple Providers

---

libs/dapp-config/src/chains/evm/index.tsx
libs/web3-api-provider/src/utils/getViemClient.ts
tools/scripts/fetchingOnChainConfig.ts

- Fix the rate limit issue in the `getViemChain` function as it does not use chain in the chainsConfg.
- Closes `NaN`

The `getViemChain` function should use chain in the chainsConfig

---

.github/workflows/deploy-faucet.yml
.github/workflows/deploy-hubble-stats.yml
.github/workflows/deploy-tangle-website.yml
apps/faucet/CHANGELOG.md
apps/faucet/package.json
apps/faucet/src/pages/_document.tsx
apps/stats-dapp/CHANGELOG.md
apps/stats-dapp/package.json
apps/tangle-website/CHANGELOG.md
apps/tangle-website/package.json
apps/webbsite/CHANGELOG.md
apps/webbsite/package.json

**⚠️ Note**: This does not include the bridge dApp. Once we release the bridge dApp, the new relayer API (utilizing HTTP) will no longer be compatible with the current live relayer (WSS). Before releasing the bridge dApp, we must inform our users to withdraw all their funds and temporarily discontinue the bridge. This will allow us to update the relayer and carry out QA with the new API.
- Release apps Aug 07, 2023

[RELEASE] Faucet, DKG Stats, Tangle Website, Webbsite - Aug 07, 2023

---

.github/workflows/check-build.yml
.github/workflows/deploy-bridge-dapp-dev.yml
.github/workflows/deploy-stats-dapp-dev.yml
.github/workflows/release.yml
apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx

- Fix JS heap out of memory when releasing apps
- Update broken links
- Closes https://github.com/webb-tools/webb-dapp/issues/1504

Fix JS Heap Out Of Memory when Releasing Apps & Update Broken Links

---

apps/stats-dapp/src/gql/proposals.graphql
apps/stats-dapp/src/pages/Proposals.tsx
apps/stats-dapp/src/provider/hooks/index.ts
apps/stats-dapp/src/provider/hooks/useProposals.ts

- Adds proposal hooks in `stats-dapp` to fetch batched proposals.
- Mainly two hooks - `useBatchedProposals` and `useBatchedProposal` which returns paginated batched proposals and a single batched proposal accordingly.
- Closes #1475 
- Batched Proposals
- Batched Proposal

Adds proposal hooks in stats-dapp to fetch batched proposals

---

apps/faucet/src/config/tokens.ts
libs/dapp-config/src/anchors/anchor-config.ts

```
Bridge Address: 0x0fdc7b1C423dC042bBcbEf177090138fA4dD3d5c
Anchor Address: 0x765A081120c1760d72D09d7c4e28Aa275D7D3fad
Webb Wrapped tTNT (webbtTNT): 0x1920d33AB0EC499b23Ca655a690164961c63A076
WETH: 0x233410c6b87E2DB946D472423a1d3378F6DC91Df
MultiCall3: 0xDAfAD783A5dc54097e2FeB6684E7Ece615Cff3aA
```
**Notes**: 
- Wrapping native tokens are only allowed on Tangle, and not other chains, users are free to move `webbtTNT` to any other chain but only unwrap them on Tangle.
- The faucet only supports native tokens on (Athena, Hermes and Demeter). However, you can also get some webbtTNT by one of the two methods below:
a. directly from the Faucet.
b. by getting tTNT and using the dApp to deposit and wrap your tTNT into webbtTNT. 
_Put an …

Orbit Deployment 20230810 01

---

apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
apps/stats-dapp/src/containers/Layout/Layout.tsx
apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
libs/webb-ui-components/src/components/Footer/Footer.tsx
libs/webb-ui-components/src/components/KeyCard/KeyCard.tsx

- Fixes extra spacing below stats footer.
- Fixes key details page compressed key copy button's flex.
- Fixes proposal data text color in proposal details page in light mode.
- Closes #1545 
- Closes https://github.com/webb-tools/webb-dapp/issues/1351

Stats dApp Fixes: footer, compressed key flex & proposal detail page color

---

apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
apps/stats-dapp/src/provider/hooks/useAuthorities.ts
libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
libs/webb-ui-components/src/components/Tooltip/Tooltip.tsx

- Adds `Rotated` status to key `Timeline` component in `Key Details` page.
- Adds a spinner to `Authorities Table` when in loading state.
- Now `Keygen Table` in `Authority Detail` page shows `Public Key` value.
- Closes #1260 
https://github.com/webb-tools/webb-dapp/assets/53374218/844a3bd6-d0e5-46a6-9967-395b248f1926

Stats dApp fixes and adds rotated key status to key timeline

---

apps/bridge-dapp/src/components/Header/Header.tsx
apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
apps/bridge-dapp/src/pages/Hubble/Bridge/SelectRelayer.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useFeeCalculation.ts
apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useRelayerWithRoute.ts
apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useTransferButtonProps.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useFeeCalculation.ts
apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useRelayerWithRoute.ts
apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useWithdrawButtonProps.tsx
apps/bridge-dapp/src/utils/validateNoteLeafIndex.ts
libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
libs/react-hooks/src/relayer/useRelayers.ts
libs/web3-api-provider/src/webb-provider/relayer-manager.ts

- Leaf heuristic checking should check on source chain id instead of dest chain id.
- Update the relayer when user chooses a different chain or pool that the current active relayer is not supported.

[HOTFIX] Leaf Index Checking & Relayer State

---

apps/bridge-dapp/src/components/Header/WalletModal.tsx
apps/bridge-dapp/src/constants/sidebar.ts
libs/webb-ui-components/src/constants/index.ts
yarn.lock

Before, users reconnecting their wallet were always defaulted to the Goerli chain, regardless of their prior chain choice. Now, first-time users are directed to the Goerli chain, while returning users will connect to their most recent chain.
- Closes #1657 
- Closes #1674 
https://github.com/webb-tools/webb-dapp/assets/53374218/925c4d56-97dd-4696-bcc8-8cb00e26ae68

Remove forced goerli connection on wallet reconnect

---

apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx

- Fixes previous session's active period incorrect progress bar. This issue occurs only when a session rotation happens soon after (not after session height) previous session rotation block (maybe like 10 -15 blocks after prev session rotation block).
- We should show full progress bar for all the previous keys other than current key. This PR fixes that.
- Closes #1605 
**Current Key**:
**Previous key before fix**:
**Previous key after fix (Progress bar is full)**:

Fix prev session's active period incorrect progress bar

---

apps/bridge-dapp/src/pages/Hubble/Bridge/SelectToken.tsx

- Show's zero balance instead of yellow warning badge.
- Closes #1710 
-----

Fix warning badge 0 balance state

---

apps/bridge-dapp/src/containers/Layout/Layout.tsx
libs/webb-ui-components/src/components/Banner/Banner.tsx
libs/webb-ui-components/src/components/SideBar/SideBar.tsx

- Adds banner on the hubble bridge to open faucet.
- Removes sidenav chevron on hover (open & close sidenav control).
- Closes #1712 
https://github.com/webb-tools/webb-dapp/assets/53374218/07de0e06-4ba5-45bb-9e40-76560ab493f8

Adds faucet banner link to bridge dapp

---

apps/bridge-dapp/src/containers/TxInfoContainer/TxInfoContainer.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/index.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
libs/webb-ui-components/src/components/TransactionInputCard/TransactionInputCard.tsx

- Deposit: Replace `wallet balance` with `shielded balance` in `destination transaction input`
- Transfer: replace `amount input` with the `remaining amount` (amount input - fees) in `destination transaction input`
- Withdraw: same as Transfer + disable MaxAmountButton in `source transaction input` when in fixed amount mode
- Remove the remaining amount in `TxInfoContainer`
- Closes #1727 
https://github.com/webb-tools/webb-dapp/assets/69841784/b07990e3-a6af-4743-9d6e-4d76f32ebd58
-----
_Please be sure to add .stories documentation if any additions are made to …

Improve balance display across all flows on Hubble Bridge

---

apps/bridge-dapp/src/hooks/useAmountWithRoute.ts

- Fix "Decimal input in amount field gets auto-deleted" in Bridge
- Closes #1737 
https://github.com/webb-tools/webb-dapp/assets/69841784/5ccd4964-7519-4aa2-95d2-4e822da83ef9
---

Fix Decimal input in amount field gets auto-deleted

---

apps/bridge-dapp/src/components/Header/Header.tsx
apps/bridge-dapp/src/containers/Layout/Layout.tsx
apps/bridge-dapp/src/pages/Hubble/Bridge/index.tsx
apps/hubble-stats/containers/Layout/Layout.tsx

- Align Margins and Width in Hubble Bridge and Hubble Statistics
- Minor UI Update on Bridge
- Navigate to Hubble Stats instead of DKG Stats when it 'Explore Stats' button on bridge
- Closes #1616
https://github.com/webb-tools/webb-dapp/assets/69841784/33ed3c73-b581-4f4f-8933-0e2568b7e727
https://github.com/webb-tools/webb-dapp/assets/69841784/7211c993-d142-44f9-9d43-a9455e19936b
---

Align Margins and Width in Hubble Bridge and Hubble Statistics

---

apps/tangle-dapp/app/page.tsx
apps/tangle-dapp/components/DelegatorTable/DelegatorTable.tsx
apps/tangle-dapp/components/DelegatorTable/index.ts
apps/tangle-dapp/components/DelegatorTable/types.ts
apps/tangle-dapp/components/TableStatus/TableStatus.tsx
apps/tangle-dapp/components/TableStatus/index.ts
apps/tangle-dapp/components/TableStatus/types.ts
apps/tangle-dapp/components/index.ts
apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegationsPayoutsContainer.tsx
apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegatorTableContainer.tsx
apps/tangle-dapp/containers/DelegationsPayoutsContainer/index.ts
apps/tangle-dapp/containers/Layout/Layout.tsx
apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
apps/tangle-dapp/containers/index.ts
apps/tangle-dapp/data/DelegationsPayouts/useDelegations.ts
apps/tangle-dapp/types/index.ts
package.json
tools/tsconfig.json

- Adds initial delegations and payouts table (Does not include all the data)
- Adds different table states (Wallet not connected, No delegation, Work In-Progress)
- Delegations table shows the following data:
- Validator address
- Validator status - Active/Waiting
- Total Validator Staked (Delegated/Staked)
- Payouts table shows work in-progress temporarily.
https://github.com/webb-tools/webb-dapp/assets/53374218/d442955e-9dcb-4dcd-9884-39677a4c12c0

EVM Staking - Initial Delegations & Payouts Table

---

apps/zk-explorer/app/providers.tsx
apps/zk-explorer/components/GitHubOAuthButton/GitHubOAuthButton.tsx
apps/zk-explorer/components/Header.tsx
apps/zk-explorer/tailwind.config.js

- A `public` folder is required, otherwise the build fails.
- Added an empty public folder, using `.gitkeep` to be able to stage it into a commit.
---

Fix `zk-explorer` deployment failing on Netlify

---

apps/testnet-leaderboard/components/RankingTableSection/fetchLeaderboardData.ts
libs/dapp-config/src/chains/evm/index.tsx
libs/dapp-config/src/chains/substrate/index.tsx
libs/webb-ui-components/src/constants/index.ts

This pull request updates the testnet RPC endpoints to use the new URLs and also adds an option to opt out of the data cache when fetching leaderboard data. This ensures that the latest data is always fetched from the server.

Update testnet RPC endpoints and opt out data cache

---

libs/abstract-api-provider/src/relayer/types.ts

These attributes need to be optional. Otherwise if you create an EVM-specific RelayChainConfig you get error that it is missing 'pallets' attribute even though it shouldn't be required. Or if you create a Substrate-specific RelayChainConfig you get error that it is missing 'contracts' and 'relayerFeeConfig' even though they aren't relevant for Substrate.

fix: Change to optional RelayerChainConfig type attributes that are EVM-specific or Substrate-specific in types.ts

---

apps/tangle-dapp/utils/polkadot/nominators.ts

-  Fixes `getValidatorIdentity` function to return validator identity display name.
- Closes #2153

fix(tangle-dapp): getValidatorIdentity function

---

apps/tangle-dapp/components/account/Actions.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/DemocracyBalance.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/DemocracyUnlockAction.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/LockedBalanceDetails.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/TextCell.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingRemainingBalances.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingSchedulesUnlockingAt.tsx
apps/tangle-dapp/containers/ManageProfileModalContainer/Independent/IndependentAllocationStep.tsx
apps/tangle-dapp/containers/ManageProfileModalContainer/Shared/SharedAllocationStep.tsx
apps/tangle-dapp/data/payouts/usePayoutsAvailability.ts
apps/tangle-dapp/data/usePayoutsAvailability.ts

_(Most of the changes above I actually added in another PR that's why you may not see them here)_
- Closes #2149
https://github.com/webb-tools/webb-dapp/assets/101931215/52b0a18b-1fc8-4c44-8b14-b4993c216c2a
---

feat(tangle-dapp): Add `Remaining` column to locked balance details

---

apps/tangle-dapp/components/NetworkSelector/NetworkSelectionButton.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
apps/tangle-dapp/containers/KeyStatsContainer/KeyStatsContainer.tsx
apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
apps/tangle-dapp/containers/WalletAndChainContainer/WalletAndChainContainer.tsx
apps/tangle-dapp/data/balances/useBalances.ts
apps/tangle-dapp/data/balances/useBalancesLock.ts
apps/tangle-dapp/data/democracy/useDemocracy.ts
apps/tangle-dapp/data/payouts/usePayouts2.ts
apps/tangle-dapp/data/vesting/useVestingInfo.ts
apps/tangle-dapp/hooks/useIsFirstTimeNominator.ts
apps/tangle-dapp/hooks/usePolkadotApiRx.ts
apps/tangle-dapp/hooks/useStakingLedgerRx.ts

- Update `usePolkadotApiRx` no longer depend on `activeSubstrateAddress`
- Show Network Dropdown even with no wallet connection
- Show Key Stats and Validators Table even with no wallet connection
- Closes #2180 
https://github.com/webb-tools/webb-dapp/assets/69841784/120ccd4e-7985-498e-ab58-02b486da6585
---

Show Network Dropdown, Key Stats and Validators Table even with no wallet connection

---

apps/tangle-dapp/components/DelegatorTable/DelegatorTable.tsx
apps/tangle-dapp/components/PayoutTable/PayoutTable.tsx
apps/tangle-dapp/components/Sidebar/Sidebar.tsx
apps/tangle-dapp/components/Sidebar/SidebarMenu.tsx
apps/tangle-dapp/components/Sidebar/sidebarProps.ts
apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
libs/webb-ui-components/src/components/SideBar/types.ts
package.json
yarn.lock

- Disabling the validator page on production.
- Adding environments property to sidebar item.
- Closes https://github.com/webb-tools/webb-dapp/issues/2191
---
https://github.com/webb-tools/webb-dapp/assets/60747384/bd673794-3253-4f4d-a205-e25a0e4a47c8

chore(tangle-dapp): Hide Development Pages & Features

---

apps/tangle-dapp/components/NetworkSelector/NetworkSelectorDropdown.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/LockedBalanceDetails.tsx
libs/webb-ui-components/src/constants/networks.ts

- Add mainnet network to network selector
- Fixed `Nomination` row shown in locked balance details even when the user is not participating in staking or has zero staking lock balance.
- Closes
https://github.com/webb-tools/webb-dapp/assets/101931215/c5a0572d-a770-47d9-837d-9a488e1351ed
---

fix(tangle-dapp): Add mainnet network to network selector

---

apps/tangle-dapp/components/account/AccountAddress.tsx
apps/tangle-dapp/components/account/ActionItem.tsx
apps/tangle-dapp/components/account/Actions.tsx
apps/tangle-dapp/components/account/WithdrawEVMBalanceAction.tsx
apps/tangle-dapp/data/balances/usePendingEVMBalance.ts
apps/tangle-dapp/utils/polkadot/tokens.ts
libs/icons/src/RefundLineIcon.tsx
libs/icons/src/Spinner.tsx
libs/icons/src/index.ts
libs/webb-ui-components/src/constants/networks.ts

- Closes #2192 
---
**_Substrate transfers_**
https://github.com/webb-tools/webb-dapp/assets/60747384/c444465d-a82d-4b2d-ac8d-289766008503
**_EVM transfers_**
https://github.com/webb-tools/webb-dapp/assets/60747384/7ba5aece-4101-441e-a24c-aad1f6152f2c

feat(tangle-dapp): EVM Transfers

---

apps/tangle-dapp/components/account/Balance.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx

- Account summary card should be displaying `free` balance instead of `transferrable` balance.
- Transferrable balance is now shown under the `Manage balances` table.
- The user can now see their total balance (`free`) and how much they can transfer at the moment (`transferrable`).
- Closes
---

fix(tangle-dapp): Use proper balance for account summary card

---

apps/tangle-dapp/components/account/Balance.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx

- Account summary card should be displaying `free` balance instead of `transferrable` balance.
- Transferrable balance is now shown under the `Manage balances` table.
- The user can now see their total balance (`free`) and how much they can transfer at the moment (`transferrable`).
- Closes
---

fix(tangle-dapp): Use proper balance for account summary card (#2209)

---

apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingRemainingBalances.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingScheduleBalances.tsx
apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingSchedulesUnlockingAt.tsx

- Vesting schedules are now sorted in ascending order, with the ones unlocking nearest shown first.
- This is more intuitive and easier on the eyes especially for users with multiple vesting schedules. 
- Closes #2217
---

feat(tangle-dapp): Sort vesting schedules in ascending order

---

apps/tangle-dapp/app/claim/EligibleSection.tsx
apps/tangle-dapp/app/page.tsx
apps/tangle-dapp/components/AmountInput/BaseInput.tsx
apps/tangle-dapp/components/Breadcrumbs/Breadcrumbs.tsx
apps/tangle-dapp/components/InfoIconWithTooltip/InfoIconWithTooltip.tsx
apps/tangle-dapp/components/KeyStatsItem/KeyStatsItem.tsx
apps/tangle-dapp/components/NetworkSelector/NetworkSelectionButton.tsx
apps/tangle-dapp/components/NetworkSelector/NetworkSelectorDropdown.tsx
apps/tangle-dapp/components/Sidebar/Sidebar.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
apps/tangle-dapp/containers/KeyStatsContainer/ActualStakedPercentageKeyStat.tsx
apps/tangle-dapp/containers/KeyStatsContainer/IdealStakedPercentageKeyStat.tsx
apps/tangle-dapp/containers/KeyStatsContainer/InflationPercentageKeyStat.tsx
apps/tangle-dapp/containers/Layout/FeedbackBanner.tsx
apps/tangle-dapp/containers/ManageProfileModalContainer/InputAction.tsx
apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
apps/tangle-dapp/containers/TransferTxContainer/TransferTxContainer.tsx
apps/tangle-dapp/hooks/useLocalStorage.ts
libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
libs/webb-ui-components/src/components/SideBar/Item.tsx
libs/webb-ui-components/src/constants/networks.ts

- Closes #2208
https://github.com/webb-tools/webb-dapp/assets/101931215/894d71c9-389c-4852-9634-31cd27491bbe
---

style(tangle-dapp): Post-launch visual improvements & fixes

---

apps/bridge-dapp/src/App.tsx
apps/tangle-dapp/components/NetworkSelector/NetworkSelectionButton.tsx
apps/tangle-dapp/containers/TransferTxContainer/TransferTxContainer.tsx
apps/tangle-dapp/containers/WalletModalContainer/WalletModalContainer.tsx
apps/tangle-dapp/hooks/useAgnosticTx.ts
apps/tangle-dapp/hooks/useEvmPrecompileAbiCall.ts
apps/tangle-dapp/hooks/useSubstrateTx.ts
libs/api-provider-environment/src/ConnectWallet/index.ts
libs/api-provider-environment/src/WebbProvider/index.tsx
libs/api-provider-environment/src/webb-context/webb-context.ts
libs/dapp-config/src/chains/evm/index.tsx
libs/dapp-config/src/chains/substrate/index.tsx
libs/dapp-config/src/constants.ts
libs/dapp-config/src/wallets/wallet-config.interface.ts
libs/dapp-config/src/wallets/wallets-config.tsx
libs/dapp-types/src/ChainId.ts
libs/dapp-types/src/EVMChainId.ts
libs/dapp-types/src/SubstrateChainId.ts
libs/react-hooks/src/useWallets.ts
libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx

- Removed hardcoded application name.
- Reset the state when the transfer model closes.
- Add or switch chain on EVM wallets to the active chain on the Tangle dApp.
- Closes https://github.com/webb-tools/webb-dapp/issues/2213
- Closes https://github.com/webb-tools/webb-dapp/issues/2214
- Closes https://github.com/webb-tools/webb-dapp/issues/2216
---
https://github.com/webb-tools/webb-dapp/assets/60747384/400162bc-a847-413c-bd06-4ea1cfe33dfb

fix(tangle-dapp): Tangle dApp Mainnet Iteration Apr 10

---

apps/tangle-dapp/containers/WalletModalContainer/WalletModalContainer.tsx

- Disable the `Wallet Connect` wallet from the Connect wallet modal temporarily, as it is currently broken.
- Should be re-enabled once the issue is addressed and fixed.
- Closes
---

refactor(tangle-dapp): Disable `Wallet Connect` wallet

---

apps/bridge-dapp/src/components/Header/Header.tsx
apps/faucet/src/components/Header.tsx
apps/faucet/src/constants/sidebar.ts
apps/hubble-stats/containers/Layout/Header.tsx
apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
apps/tangle-dapp/app/claim/success/SuccessClient.tsx
apps/tangle-dapp/app/services/[serviceId]/JobsListTable.tsx
apps/tangle-dapp/components/KeyStatsItem/KeyStatsItem.tsx
apps/tangle-dapp/components/TxConfirmationModal/TxConfirmationModal.tsx
apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
apps/tangle-dapp/hooks/useExecuteTxWithNotification.tsx
apps/tangle-dapp/hooks/useExplorerUrl.ts
apps/tangle-dapp/hooks/useTxExplorerUrl.ts
apps/tangle-dapp/types/index.ts
apps/testnet-leaderboard/components/Navbar.tsx
libs/api-provider-environment/src/transaction/utils/getExplorerURI.ts
libs/dapp-config/src/chains/evm/index.tsx
libs/dapp-config/src/chains/substrate/index.tsx
libs/dapp-config/src/constants/index.ts
libs/dapp-config/src/constants/tangle.ts
libs/webb-ui-components/src/constants/index.ts
libs/webb-ui-components/src/constants/networks.ts

- Navigate users to correct tx and account page on block explorer (both EVM & Substrate)
- Update chains-config in `dapp-config`
- Update `getUrlExplorer` function that handle substrate case successfully
- Unify constants related to `Tangle` inside `dapp-config`
- Closes #2224
https://github.com/webb-tools/webb-dapp/assets/69841784/5594d467-75ff-4b28-8842-1ada33e9a2b6
---

Update Explorer links on Tangle Dapp + getUrlExplorer + Chains Config

---

apps/tangle-dapp/app/nomination/loading.tsx
apps/tangle-dapp/components/KeyStatsItem/KeyStatsItem.tsx
apps/tangle-dapp/components/TangleTokenIcon.tsx
apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
apps/tangle-dapp/containers/KeyStatsContainer/ActiveValidatorsKeyStat.tsx
apps/tangle-dapp/containers/KeyStatsContainer/KeyStatsContainer.tsx
apps/tangle-dapp/containers/KeyStatsContainer/ValidatorCountKeyStat.tsx
apps/tangle-dapp/containers/KeyStatsContainer/WaitingValidatorsKeyStat.tsx
apps/tangle-dapp/containers/Layout/Layout.tsx

- Update Key Stats Container to have 3 columns in the desktop display for less clutter display
- Fix Footer not bottom bound
- Add static icon for Tangle Token
- Closes #2244 
- Closes #2246 
- Closes #2252
https://github.com/webb-tools/webb-dapp/assets/69841784/0e9db169-1553-4a32-b018-1500a70c55f2
---

UI improvements on Tangle Dapp (Key Stats Item + Fix Footer bottom bound + Static Tangle Icon)

---

apps/tangle-dapp/app/restake/RoleDistributionCard/DistributionChart.tsx
apps/tangle-dapp/app/restake/page.tsx
apps/tangle-dapp/components/Sidebar/Sidebar.tsx
apps/tangle-dapp/components/Sidebar/sidebarProps.ts
apps/tangle-dapp/constants/index.ts
apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
apps/tangle-dapp/context/useNetworkStore.ts
apps/tangle-dapp/data/restaking/useRestakingProfile.ts
apps/tangle-dapp/hooks/useLocalStorage.ts
apps/tangle-dapp/hooks/useNetworkState.ts
apps/tangle-dapp/utils/convertAmountStringToChainUnits.ts
apps/tangle-dapp/utils/createCustomNetwork.ts
apps/tangle-dapp/utils/evm/createTangleViemChainFromNetwork.ts
apps/tangle-dapp/utils/formatBnToDisplayAmount.ts
apps/tangle-dapp/utils/polkadot/tokens.ts
libs/dapp-config/src/chains/substrate/index.tsx
libs/dapp-config/src/constants/tangle.ts
libs/webb-ui-components/src/constants/networks.ts

- Have the token unit be hardcoded instead of dynamic
- Add new Tangle constants for universal use
- Remove EVM Explorer URL for local Tangle
- Closes #2249 
---

Have the native token symbol be hardcoded instead of dynamic to improve performance

---

apps/tangle-dapp/components/account/Balance.tsx
apps/tangle-dapp/utils/polkadot/tokens.ts

- Enhance the balance display to show the full amount, thus reducing confusion for users.
- Closes https://github.com/webb-tools/webb-dapp/issues/2280
**_Before_**
https://github.com/webb-tools/webb-dapp/assets/60747384/5a158e7f-3a0b-4fcc-949f-695cc650467a
**_After_**
https://github.com/webb-tools/webb-dapp/assets/60747384/b3442519-3d81-45d8-98f8-de57a6212051

fix(tangle-dapp): Improve Balance Display

---

apps/tangle-dapp/app/loading.tsx
apps/tangle-dapp/app/page.tsx
libs/webb-ui-components/src/components/SkeletonLoader/SkeletonLoader.tsx
libs/webb-ui-components/src/components/SkeletonLoader/utils.ts
libs/webb-ui-components/src/typography/Typography/Typography.tsx
libs/webb-ui-components/src/typography/types.ts

- Added loading account page to enhance First Contentful Paint time.
- Closes https://github.com/webb-tools/webb-dapp/issues/2240

feat(tangle-dapp): Added Loading Account Page

---

apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
apps/tangle-dapp/data/payouts/store.ts
apps/tangle-dapp/data/payouts/useClaimedRewards.ts
apps/tangle-dapp/data/payouts/useErasRewardsPoints.ts
apps/tangle-dapp/data/payouts/useNominationsUnclaimedRewards.ts
apps/tangle-dapp/data/types.ts
libs/api-provider-environment/src/WebbProvider/index.tsx

- Optimized `usePayouts` hook.
- Display the loading state on the nomination and payout tables.
- Loading should be `false` by default on `WebbProvider`.
- Closes https://github.com/webb-tools/webb-dapp/issues/2327
---
_Before_
_After_

perf(tangle-dapp): Optimize `usePayouts` hook

---

apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
apps/tangle-dapp/data/ValidatorTables/useValidatorIdentityNames.ts
apps/tangle-dapp/data/payouts/store.ts
apps/tangle-dapp/data/payouts/useClaimedRewards.ts
apps/tangle-dapp/data/payouts/useEraTotalRewards.ts
apps/tangle-dapp/data/payouts/useNominationsUnclaimedRewards.ts

- Memorized calculations & functions to avoid unnecessary re-renders.
- Added an abort signal to cancel the previous call.
- Added an identity map to avoid multiple requests for validators' identities.
- Closes `NaN`

fix(tangle-dapp): Fixing Infinite `useEffect` Calls

---

apps/tangle-dapp/hooks/useInputAmount.ts

- Fix the bug that the input amount does not allow 0.0, 10.00, etc.
- Closes #2412 
https://github.com/webb-tools/webb-dapp/assets/69841784/448f1059-bb61-4eba-9e81-68b3e27ca442
---

fix(tangle-dapp): Fix Amount Input

---

apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts

- `data` is changed when `setPayouts` is called, yet `data` is a dependency of the `useEffect`, thus leading to a cycle.
- Fixed by taking the condition check outside of the `useEffect`.
- Bug seems to appear only when there are **no** available payouts in the user's account.
- Closes
---

fix(tangle-dapp): Fix `useEffect` cycle in `usePayouts` hook

---

apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/WithdrawUnlockNftButton.tsx
apps/tangle-dapp/constants/liquidStaking/constants.ts
apps/tangle-dapp/constants/liquidStaking/devConstants.ts
apps/tangle-dapp/constants/liquidStaking/multicall3Abi.ts
apps/tangle-dapp/data/liquifier/useContractReadBatch.ts
apps/tangle-dapp/data/liquifier/useContractWrite.ts
apps/tangle-dapp/data/liquifier/useContractWriteBatch.ts
apps/tangle-dapp/data/liquifier/useLiquifierWithdraw.ts

- 🔧 Calls to `Liquifier.sol::withdraw` are now batched to enable redemption of multiple NFTs within a single transaction. Before, it had to be done via sequential transactions, which greatly affects UX for larger numbers of unlock NFTs.
- ➕ Created `useContractWriteBatch` reusable hook which utilizes [`multicall3` contract](https://github.com/mds1/multicall) to batch transactions. This hook can be used for other transactions that may require batching in the future.
- Closes #2522
---
_Please be sure to add .stories documentation if any additions are made to …

feat(tangle-dapp): Use `multicall3` contract to batch Liquifier withdraw calls

---

apps/tangle-dapp/CHANGELOG.md
apps/tangle-dapp/components/Sidebar/sidebarProps.ts
apps/tangle-dapp/package.json

- Release tangle dApp `v0.0.14`
- Closes `NaN`

[RELEASE] tangle-dapp v0.0.14

---

libs/webb-ui-components/src/components/Pagination/Pagination.tsx

- Handle empty title on Pagination component.
- Closes `NaN`

feat: handle properly empty title on Pagination

---

apps/tangle-dapp/components/LiquidStaking/LsMyPoolsTable.tsx
apps/tangle-dapp/containers/LsPoolsTable/LsPoolsTable.tsx
apps/tangle-dapp/data/liquidStaking/useLsPools.ts
apps/tangle-dapp/utils/liquidStaking/tryEncodeAddressWithPrefix.ts
libs/webb-ui-components/src/components/Pagination/Pagination.tsx

- ➕ On the liquid staking pool tables, when an avatar is hovered, its full address is displayed in a tooltip. This helps users recognize validators.
- 🐛 Fixed a small bug related to a missing space in the Pagination component's title.
- Closes #2639

feat(tangle-dapp): Show validator address when avatar is hovered

---

libs/webb-ui-components/src/components/ChainChip/ChainChip.tsx

- Fixes the chain name in the chain chip component within the transaction queue item.
- Closes

fix(tangle-dapp): Chain display name

---

apps/tangle-dapp/src/components/BlueIconButton.tsx
apps/tangle-dapp/src/components/account/ActionItem.tsx
apps/tangle-dapp/src/constants/index.ts
apps/tangle-dapp/src/containers/BalancesTableContainer/BalanceAction.tsx
apps/tangle-dapp/src/containers/BalancesTableContainer/BalanceCell.tsx
apps/tangle-dapp/src/containers/BalancesTableContainer/LockedBalanceDetails/TextCell.tsx
apps/tangle-dapp/src/containers/PayoutTxContainer/PayoutTxContainer.tsx
apps/tangle-dapp/src/containers/restaking/JoinOperatorsBanner.tsx
apps/tangle-dapp/src/containers/restaking/JoinOperatorsModal.tsx
apps/tangle-dapp/src/data/restake/useJoinOperatorsTx.ts
apps/tangle-dapp/src/hooks/useInputAmount.ts
apps/tangle-dapp/src/hooks/useTxNotification.tsx
apps/tangle-dapp/src/pages/restake/overview/index.tsx
libs/tangle-shared-ui/src/components/blueprints/RestakeBanner.tsx
libs/webb-ui-components/src/components/Avatar/Avatar.tsx
libs/webb-ui-components/src/components/BridgeInputs/InfoItem.tsx
libs/webb-ui-components/src/components/Caption.tsx
libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
libs/webb-ui-components/src/components/CircularProgress.tsx
libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
libs/webb-ui-components/src/components/ListCard/TokenListItem.tsx
libs/webb-ui-components/src/components/Modal/ModalFooterActions.tsx
libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
libs/webb-ui-components/src/components/TokenPairIcons/TokenPairIcons.tsx
libs/webb-ui-components/src/components/Tooltip/Tooltip.tsx
libs/webb-ui-components/src/components/buttons/Button.tsx
libs/webb-ui-components/src/components/buttons/types.ts
libs/webb-ui-components/src/containers/ConfirmationCard/AmountInfo.tsx
libs/webb-ui-components/src/containers/ConfirmationCard/RefundAmount.tsx

- ➕ Added the `Join Operator` banner, button and modal, as well as the transaction logic.
- ➕ Added a prop for the `Button` component which allows a tooltip to be displayed when it is disabled.
- Closes #2741
banner & button:
modal:
when an evm account is connected:
mobile viewport:
mobile viewport modal:

feat(tangle-dapp): Add `Join Operator` button & modal

---

apps/tangle-dapp/src/components/KeyStatsItem/KeyStatsItem.tsx
apps/tangle-dapp/src/components/account/RewardsAndPoints.tsx
apps/tangle-dapp/src/data/rewards/useAccountRewardInfo.ts

- Add an option to disable error notifications for the KeyStatsItem component.
- Do not throw an error when fetching rewards.
- Avoid retrying on errors when fetching rewards.

fix(tangle-dapp): Improve Error Handling When Parsing Response

---

apps/tangle-dapp/src/components/ErrorMessage.tsx
apps/tangle-dapp/src/components/Sidebar/sidebarProps.ts
apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx
apps/tangle-dapp/src/components/bridge/FeeDetail.tsx
apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
apps/tangle-dapp/src/pages/liquid-staking/index.tsx
apps/tangle-dapp/src/pages/nomination/index.tsx

fix(tangle-dapp): Bridge UI fixes

---

libs/dapp-config/src/types.ts
libs/dapp-config/src/utils/findSubstrateWallet.ts
libs/dapp-config/src/wallets/wallet-config.interface.ts
libs/dapp-config/src/wallets/wallets-config.tsx
libs/dapp-types/src/WalletId.ts
libs/polkadot-api-provider/src/ext-provider/polkadot-provider.ts
libs/polkadot-api-provider/src/webb-provider.ts
libs/tangle-shared-ui/src/components/UpdateMetadataButton/UpdateMetadataButton.tsx
libs/tangle-shared-ui/src/hooks/usePromise.ts
libs/tangle-shared-ui/src/hooks/useSubstrateInjectedExtension.ts
libs/tangle-shared-ui/src/hooks/useWallet.ts
libs/tangle-shared-ui/src/utils/polkadot/api.ts
types/global.d.ts

- Fix the issue of the Talisman wallet repeatedly appearing during page re-renders.
- Ensure that only the selected wallet opens when connecting to a Substrate wallet, rather than all available Substrate wallets.
- Call `web3Enable` only once, and use `web3EnablePromise` if it is initialized. 
- **Note:** _Ideally, avoid calling `web3Enable` as it triggers the connection for all installed Substrate wallets._
- Utilize the injected extension from the active API instead of reinitializing and searching for the target extension, which also causes all unconnected Substrate wallets to appear.
- Simplify the `sign` method by directly using the injected extension signer from the API.
_Specify any issues …

fix(tangle-shared-ui): Fix Talisman Keep Popping Up

---

libs/dapp-config/src/chains/evm/customChains/tangleMainnetEVM.ts
libs/dapp-config/src/chains/evm/customChains/tangleTestnetEVM.ts

Update Tangle's testnet and mainnet chain information to match the Ethereum chain list [testnet](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-3799.json) and [mainnet](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-5845.json) to avoid warnings when users add the chain to their EVM wallet.
| Testnet  | Mainnet |
| ------------- | --------------- |
| <img src="https://github.com/user-attachments/assets/350f8013-51f5-4afa-b271-913ad4493a7a" alt="CleanShot 2025-03-06 at 01 26 …

fix(tools): Update Tangle chains Info

---

apps/tangle-dapp/src/features/bridge/hooks/useAssets.ts

- Fixed a crash on the bridge page that occurred when the dApp was connected to a Substrate account.
https://github.com/user-attachments/assets/4ce54b90-dec1-416a-abd4-785f15b0f177

fix(tangle-dapp): Fix bridge page crash when connected to a Substrate account

---

apps/tangle-dapp/src/features/bridge/components/BridgeActionButton.tsx
apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletButton.tsx

- If the user is connected to a non-EVM wallet on the bridge page, they will be prompted to switch to compatible wallet before performing any bridge action.
- Closes #2824
https://github.com/user-attachments/assets/985a8e06-3477-48f0-b725-1fa79559afa7

chore(tangle-dapp): Add switch wallet button for bridge

---

apps/tangle-dapp/src/components/account/RewardsAndPoints.tsx
apps/tangle-dapp/src/components/tables/Vaults/index.tsx

- 🔧 Small change: Tables & rewards should use `0` if there's no deposits or data, instead of `--` which should be used for loading/unavailable states.
- Closes #2831

refactor(tangle-dapp): Use 0 instead of value placeholders

---

apps/tangle-dapp/src/components/tables/Vaults/index.tsx
libs/tangle-shared-ui/src/data/restake/useRestakeAssetIds.ts
libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
libs/tangle-shared-ui/src/data/rewards/useVaultRewards.ts
libs/tangle-shared-ui/src/data/rewards/useVaultsPotAccounts.ts
libs/tangle-shared-ui/src/hooks/useApiRx.ts
libs/tangle-shared-ui/src/hooks/usePromise.ts
libs/tangle-shared-ui/src/types/error.ts

- `usePromies`' `isLoading` should default to `false`.
- Reset `result` in `useApiRx` on RPC change.
- Data hooks should return errors for invalid arguments.
- Vault table should use `isLoading` prop for loading state, not `data`.

fix(tangle-shared-ui): Fix Incorrect Vault Data Display

---

apps/tangle-cloud/netlify.toml

- Improve the release process by adding a Netlify build ignore.
- 🚩 Currently, merging `develop` into `master` triggers a full monorepo redeploy in Netlify, even though only the released dApp should be updated.
- 💡 The solution is to configure Netlify build ignore for each dApp, so it only redeploys on `master` if changes are detected within the dApp's `CHANGLOG.md` file.

ci(tools): Add Netlify Build Ignore to Improve Release Process

---

apps/tangle-dapp/src/components/LiquidStaking/LsMyPoolsTable.tsx
apps/tangle-dapp/src/containers/LsMyProtocolsTable.tsx

- ➕ Loading & disconnected wallet states are now shown for the liquid staking 'My Pools' table.
- Closes #2908

feat(tangle-dapp): Add LS pools loading state

---

.github/CODEOWNERS
package.json
scripts/setupRestaking.ts
scripts/setupServices.ts
scripts/util.ts

- ➕ Created a script to easily setup a testing environment for local dev when testing restaking actions (deposit, delegate, etc.). This is useful because it automates the need to manually setup a test env every time a local node is restarted.
- ➕ Created a similar script but for setting up blueprints & services for testing. This is mainly useful for Tangle Cloud.
**Note**: Running these scripts requires [Bun](https://bun.sh/). I think this is a good idea to avoid having to compile the TypeScript files -- or worse yet, having them be in JS. Here's how you might run the scripts after you've installed Bun:
```sh
yarn script:setupRestaking # create LST & prepare for restaking actions
yarn script:setupServices # create blueprints
```
We can …

feat(tangle-dapp): Create restaking & services setup scripts

---

.windsurfrules
apps/tangle-dapp/src/components/Lists/AssetListItem.tsx
apps/tangle-dapp/src/components/restaking/TabListItem.tsx
libs/dapp-config/src/chains/substrate/index.tsx
libs/tangle-shared-ui/src/components/ConnectWalletButton/WalletDropdown.tsx

- Fixes asset modal list inconsistent UI between connection to substrate and EVM wallet
- Fixes restake action tabs padding
- Fixes text wrapping of the account name when it is too long
- Updates `Tangle Mainnet Native` to `Tangle Mainnet` in connected chain component
- Adds `.windsurfrules` file
https://github.com/user-attachments/assets/cedd94c8-4bf9-4a6f-be67-b5b5a5d34287

fix(tangle-dapp): Asset modal, restake action tabs & wallet dropdown fixes

---

apps/tangle-cloud/src/components/Layout.tsx
apps/tangle-cloud/src/components/Sidebar.tsx
apps/tangle-cloud/src/pages/instances/InstructionCard.tsx
libs/ui-components/src/components/TableAndChartTabs/TableAndChartTabs.tsx

- Fixes sidebar layout
- Fixes tabs colors
- Fixes instruction component alignment
- Closes #2978 
https://github.com/user-attachments/assets/b2b2824c-d554-4518-ae38-24c7887a219e

fix(tangle-cloud): sidebar, tab colors & instruction component fixes

---

apps/tangle-cloud/src/pages/instances/InstructionCard.tsx
apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
apps/tangle-dapp/src/containers/restaking/RestakeTabContent.tsx
apps/tangle-dapp/src/pages/restake/delegate/index.tsx
libs/tangle-shared-ui/src/data/restake/useRestakeOperatorMap.ts

- `tangle-dapp`: fixes empty operators list in restake page and select operator modal of delegate restake action
- `tangle-cloud`: fixes instruction component colors in light/dark mode
https://github.com/user-attachments/assets/08258321-8a42-4618-8d38-01f44fc264dd

fix(tangle-dapp): Fixes empty operators list in restake page

---

apps/tangle-cloud/src/pages/blueprints/ConfigureBlueprintModal/types.ts
apps/tangle-cloud/src/pages/blueprints/[id]/page.tsx
apps/tangle-cloud/src/pages/blueprints/page.tsx
apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
apps/tangle-dapp/src/pages/blueprints/BlueprintListing.tsx
apps/tangle-dapp/src/pages/blueprints/[id]/index.tsx
libs/tangle-shared-ui/src/components/blueprints/BlueprintHeader.tsx
libs/tangle-shared-ui/src/components/blueprints/RegisteredChip.tsx
libs/tangle-shared-ui/src/components/blueprints/RestakeBanner.tsx
libs/tangle-shared-ui/src/hooks/useOperatorInfo.tsx

- Shows `registered` chip for registered blueprints and removes `Register` button
- Fixes the bug where blueprints were not displayed in `tangle-dapp` blueprints page
- Small UI fixes
- Move `useOperatorInfo` hook to `tangle-shared-ui`
- Closes #2991 
https://github.com/user-attachments/assets/666ed849-7bc9-4696-9774-62cb11b38e7b
https://github.com/user-attachments/assets/4861c55f-ef5c-4791-ac82-06932983edd6

chore(tangle-dapp): Registered blueprint chip & fix tangle-dapp blueprints page

---

apps/tangle-cloud/src/components/TangleCloudCard.tsx
apps/tangle-cloud/src/components/accountStatsCard/AccountStatsCardBody.tsx
apps/tangle-cloud/src/data/operators/useOperatorStatsData.ts
apps/tangle-cloud/src/data/operators/useUserStatsData.ts
apps/tangle-cloud/src/data/services/useUserOwnedInstances.ts
apps/tangle-cloud/src/pages/blueprints/[id]/page.tsx
apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
apps/tangle-cloud/src/pages/instances/Instances/index.tsx
apps/tangle-cloud/src/pages/instances/InstructionCard.tsx
apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
apps/tangle-cloud/src/pages/instances/page.tsx
libs/tangle-shared-ui/src/components/blueprints/RestakeBanner.tsx
libs/tangle-shared-ui/src/components/tables/Operators/index.tsx
libs/tangle-shared-ui/src/data/blueprints/useMonitoringBlueprints.ts
libs/tangle-shared-ui/src/data/blueprints/usePendingServiceRequest.ts
libs/tangle-shared-ui/src/hooks/useOperatorInfo.tsx

- add automatic table refresh after service instance state changes
- validate operator address against operator map in useOperatorInfo hook
- conditionally show operator UI based on registered blueprints
- add operator chip indicator to account stats card header
- enhance RestakeBanner with improved styling, dark mode support and hover effects
- enhance TangleCloud and instruction cards with improved ui and hover effects
- update table cell styles
- enhance operators table UI with improved dark mode and loading states
https://github.com/user-attachments/assets/0a3984b2-88df-490e-82cb-4b8b03cbd32b

fix(tangle-cloud): UI/UX Fixes & Improvements

---

.github/workflows/claude-review.yml
.github/workflows/claude.yml

- add Claude workflows for PR reviews and issue comments

ci(workflows): Add Claude workflows for PR reviews and issue comments

---

apps/leaderboard/src/utils/getRpcEndpoint.ts
apps/tangle-dapp/src/components/Lists/AssetListItem.tsx
apps/tangle-dapp/src/components/Lists/OperatorListItem.tsx
apps/tangle-dapp/src/components/Sidebar/sidebarProps.tsx
apps/tangle-dapp/src/components/Sidebar/useSidebarProps.ts
apps/tangle-dapp/src/components/account/Actions.tsx
apps/tangle-dapp/src/components/account/ProtocolStatisticCard/VaultsHightlightCard.tsx
apps/tangle-dapp/src/constants/restake.ts
apps/tangle-dapp/src/containers/restaking/WithdrawModal.tsx
apps/tangle-dapp/src/data/restake/RestakeAbiBase.ts
apps/tangle-dapp/src/data/restake/RestakeEvmApi.ts
apps/tangle-dapp/src/data/restake/RestakeSubstrateApi.ts
apps/tangle-dapp/src/pages/restake/delegate/RestakeDelegateInput.tsx
apps/tangle-dapp/src/pages/restake/delegate/index.tsx
apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
libs/dapp-config/src/chains/substrate/index.tsx
libs/dapp-config/src/constants/tangle.ts
libs/tangle-shared-ui/src/types/restake.ts
libs/tangle-shared-ui/src/utils/restake/getAssetType.ts
libs/ui-components/src/constants/networks.ts
package.json
yarn.lock

- Updated `@tangle-network/tangle-substrate-types` to `0.9.34`
- Removed Liquid Staking and Claims from sidebar
- Removed testnet faucet when connected to mainnet
- Added visual badges to distinguish between `Nominated` (purple) and `Deposited` (green) TNT assets across all restaking flows
- Enhanced logic to properly handle both nominated and deposited TNT balances
- Consistent asset naming across all flows
- Enhanced delegation calls to use delegateNomination for nominated assets vs standard delegate for deposited assets
- Removed Dwellir RPC endpoints
- Show operator names if available in operator modals
- Other minor fixes and improvements

chore(tangle-dapp): Restake Improvements & Fixes

---

apps/tangle-dapp/src/components/Lists/AssetListItem.tsx
apps/tangle-dapp/src/components/Lists/LogoListItem.tsx
apps/tangle-dapp/src/components/Lists/OperatorListItem.tsx
apps/tangle-dapp/src/constants/index.ts
apps/tangle-dapp/src/containers/restaking/SelectOperatorModalEnhanced.tsx
apps/tangle-dapp/src/containers/restaking/UnstakeRequestTable.tsx
apps/tangle-dapp/src/containers/restaking/UnstakeRequestTableActions.tsx
apps/tangle-dapp/src/data/restake/useDepositedRestakeUnstakeExecuteTx.ts
apps/tangle-dapp/src/data/restake/useNativeRestakeAssetBalance.ts
apps/tangle-dapp/src/hooks/useTxNotification.tsx
apps/tangle-dapp/src/pages/restake/delegate/index.tsx
apps/tangle-dapp/src/pages/restake/unstake/index.tsx
apps/tangle-dapp/src/utils/getAssetLabelColorClasses.ts
libs/tangle-shared-ui/src/data/restake/useRestakeDelegatorInfo.ts
libs/tangle-shared-ui/src/types/restake.ts

- Fixes restake flow bugs and adds minor UI improvements.
Note 📝
- This PR focuses on fixing bugs related to the logic for calling the `multiAssetDelegation` pallet extrinsics and on testing that all the restake flows work as intended.
- Loading states and notifications in certain flows are buggy and will be addressed in a separate PR, along with general UX improvements.
**_Restake Flow 1 (Deposit)_**
https://github.com/user-attachments/assets/a698a1ba-3916-406f-ae85-6dbe70c61b2e
**_Restake Flow 2 (Nomination)_**
https://github.com/user-attachments/assets/dcc11163-344a-4b8d-8e1f-bab4fe1d284d

chore(tangle-dapp): Restake Undelegate & Withdraw Improvements
