tangle-network/dapp

- packages/apps/src/i18n/index.json
- packages/react-components/src/layout/index.tsx
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useFetch.ts
Resolves #5 and adds useFetch for async http calls.
> Add useFetch hook and present IP to user

- packages/page-mixer/src/components/common.tsx
- packages/page-mixer/src/components/deposit/DepositConsole.tsx
- packages/page-wallet/src/components/TokenBalances.module.scss
- packages/page-wallet/src/components/TokenBalances.tsx
- packages/react-components/src/Sidebar/Logo.tsx
- packages/react-environment/src/store/modules/ui.ts
- packages/react-hooks/src/useLocalStorage.ts
- packages/react-hooks/src/useStorage.ts
- packages/react-hooks/src/utils/isSupportedCurrency.ts
- packages/ui-components/src/styles/Theme.tsx
- packages/ui-components/src/styles/global.css
- packages/ui-components/src/styles/lightTheme.tsx
- yarn.lock
> Fix light theme card colors

- packages/react-components/src/Sidebar/Logo.tsx
- packages/react-environment/src/store/modules/ui.ts
- packages/react-hooks/src/useStorage.ts
- packages/ui-components/src/styles/Theme.tsx
> Fix theme persistency after switching networks(refreshing)

- packages/apps/public/index.html
- packages/page-mixer/src/components/deposit/DepositConsole.tsx
- packages/page-mixer/src/components/deposit/SubmitDeposit.tsx
- packages/react-hooks/src/tx/useTX.tsx
> deposit modal and split TX functionality

- package.json
- packages/react-environment/src/MixerProvider.tsx
- packages/react-hooks/src/mixer/useMixer.ts
- packages/react-hooks/src/withdraw/useWithdraw.tsx
- yarn.lock
This PR will enable the dApp to kill running tasks on WasmWorker
> Integrate `WasmMixer` cancel functionality from `webbjs`

- packages/apps/src/App.tsx
- packages/mixer/src/Mixer.tsx
- packages/mixer/src/components/Withdraw/Withdraw.tsx
- packages/mixer/src/components/Withdraw/WithdrawingModal.tsx
- packages/react-components/src/AppBar/AppBar.tsx
- packages/react-components/src/BottomNavigation/BottomNavigation.tsx
- packages/react-environment/src/WebbProvider.tsx
- packages/ui-components/src/Inputs/InputLabel/InputLabel.tsx
These PR has changes to implement the following issues:
- After copying note, text on AccountsManager, withdraw modal, does not display properly
- Change name of second "Note" to "Recipient"
- Remove the entire greeting
- Some fonts in dark mode are not properly colored
- Fix ZkProff, change to zkBridge
> Nathan small UI changes

- packages/apps/public/index.html
- packages/react-environment/src/RouterProvider.tsx
These changes are necessary to have a successful IPFS deployment.
> IPFS Deployment requirements

- packages/apps/src/configs/evm/SupportedMixers.ts
Add more mixers for Harmony Testnet Shard 1
> Adding other mixer sizes for Harmony

- packages/apps/src/configs/chains/chain-config.ts
- packages/apps/src/configs/wallets/wallets-config.ts
- packages/react-environment/src/WebbProvider.tsx
- packages/react-environment/src/types/wallet-config.interface.ts
- packages/react-environment/src/webb-context/webb-context.ts
- packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
- packages/ui-components/src/Inputs/WalletSelect/WalletManger.tsx
- packages/ui-components/src/Inputs/WalletTokenInput/WalletTokenInput.tsx
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
- As a user, I can click to view all "live" chains and see only "live" production chains.
- As a user, I can click "test" and see only the available testnet chains.
- Should be improved for an 'all' or deselect.
- Default is test,
> Fixes and improvements for the chain switcher component

- packages/contracts/src/contracts/tornado-anchor.ts
- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
Move websocket connection initialization until it is needed.
Allow proof generation on leaves queried from the selected relayer to improve speeds.
> Add proof generation from leaves response of active relayer

- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
Currently, we are requiring users that select 'None' for a relayer to wait for all previous blocks to be queried for leaves. This takes a very long amount of time, and users may have a negative experience.
This change always queries available relayers for leaves - even if they are not being used to relay transactions. Users which are concerned about relayer integrity (expected to be a small contingent) can always run their own relayers.
> Default to fetching leaves from relayers even when no relayer selected

- packages/contracts/src/contracts/webb-anchor.ts
- packages/contracts/src/contracts/webb-governed-token.ts
- packages/react-environment/src/api-providers/web3/web3-bridge-withdraw.ts
It is assumed that the generated merkle proof is constructed with the latest on-chain neighbor roots.
Roots passed to the zk proof include the historical neighbor root that was used in generating the merkle proof.
> Fix inputs to use historical neighbor root used in merkle proof

- packages/bridge/src/Bridge.tsx
- packages/react-components/src/PermissionedAccess/PermissionedAccess.tsx
IP geolocation is used to block all access to tornados or bridge no matter which network.
If the selected network is a test network, offer full functionality to the user.
> Skip checking permissions if the selected network is a test network

- packages/apps/.gitignore
- packages/apps/config-overrides.js
- packages/apps/public/index.html
- packages/apps/src/App.tsx
- packages/apps/src/index.tsx
- packages/apps/src/initI18n.ts
- packages/bridge/src/components/Withdraw/Withdraw.tsx
- packages/bridge/src/components/Withdraw/WithdrawingModal.tsx
- packages/bridge/src/hooks/withdraw/useWithdraw.tsx
- packages/mixer/src/components/Withdraw/Withdraw.tsx
- packages/mixer/src/components/Withdraw/WithdrawingModal.tsx
- packages/mixer/src/hooks/withdraw/useWithdraw.tsx
- packages/react-components/src/Withdraw/WithdrawSuccessModal.tsx
- packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
- packages/utils/src/misc/app-mode.ts
- packages/utils/src/misc/get-cached-fixtures-uri.ts
- packages/utils/src/misc/index.ts
Issue Number: #240 ,#236 
- <del>Added a better way to handle the app mode `development`, `production` on the `config-overides.js`</del> ,and the two functions `isDevelopment` ,  and `isProduction` on `utils` package
- Fixed the scrollbar issue #240 
- Fixed the #236 
- forward the keys to a local file on `development` instead of fetching them every time from IPFS
- Withdrawal cancellation UI (Still need to handle the actual TX cancellation/preventing)
> Fix modals and Withdrawal cancelation UI

- packages/apps/src/configs/bridges/bridge-config.ts
- packages/react-environment/src/api-providers/web3/web3-bridge-withdraw.ts
- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
- packages/react-environment/src/webb-context/relayer/types.ts
Relayers do not work for the bridge since the client is formatting the withdraw command in a way the relayer does not expect.
Issue: #266 
The commands have been changed to what the relayer expects
> Match relayer expected command name to command base

- packages/react-components/src/AccountManager/AccountManager.tsx
- packages/react-components/src/AppBar/AppBar.tsx
- packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
- packages/ui-components/src/Page.tsx
> Fix z-index issues with popper component clipping

- packages/apps/src/router-config.tsx
- packages/apps/src/serviceWorker.ts
- packages/react-components/src/AppBar/AppBar.tsx
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
There are inline checks: `'REACT_APP_BUILD_ENV === 'development'`
There are helper functions: `app-mode.ts`
Consistent use with `app-mode.ts`
> Consistent use of environment flags

- packages/bridge/src/Bridge.tsx
- packages/mixer/src/Mixer.tsx
> Remove permissioned access

- packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
- packages/utils/src/misc/app-mode.ts
> Staging and development fixes

- README.md
> Update the readme with steps for running locally

- packages/bridge/src/components/Deposit/Deposit.tsx
- packages/react-environment/src/api-providers/web3/web3-bridge-deposit.ts
Defaulting to wrap and deposit when we should be depositing just the governed token.
Only wrap and deposit transactions when 'Wrap Assets' is checked.
> Pass currency to DepositConfirm component only if wrappable assets are selected

- README.md
- package.json
- packages/bridge/src/components/Deposit/Deposit.tsx
- packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
- packages/react-environment/src/api-providers/web3/web3-bridge-deposit.ts
- packages/utils/src/misc/app-mode.ts
> Update package.json formatting and README for release

- packages/apps/src/initI18n.ts
- packages/bridge/src/components/Deposit/Deposit.tsx
- packages/page-wrap-unwrap/src/index.tsx
- packages/react-components/src/AccountManager/AccountManager.tsx
- packages/react-components/src/AppBar/AppBar.tsx
- packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
- packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
- packages/ui-components/src/Inputs/WalletBridgeCurrencyInput/WalletBridgeCurrencyInput.tsx
- packages/ui-components/src/Inputs/WalletTokenInput/WalletTokenInput.tsx
The popper component looks strange on mobile displays. There are empty 'spacing div' elements in the application to enforce popper positioning. popper components that display off screen start to jump on the application.
Issue Number: #299 
Easier positioning of elements and change ordering of popper so the element that pops onto the DOM is just the dropdown.
> Refactor popper for easier positioning and mobile displays

- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
If the randomly selected relayer is not behaving properly when we fetch leaves from it, the user will be blocked from withdrawing even without a selected relayer.
If the relayer is not behaving properly, query from the chain directly.
> Add fix for dependency on relayer leaves for mixer proof generation

- packages/apps/src/initI18n.ts
- packages/bridge/src/components/Deposit/Deposit.tsx
- packages/bridge/src/hooks/deposit/useBridgeDeposit.tsx
- packages/react-environment/src/api-providers/polkadot/polkadot-transaction.ts
- packages/ui-components/src/Inputs/WalletBridgeCurrencyInput/WalletBridgeCurrencyInput.tsx
- Polkadot transaction success duplicate notification
- #276 
Issue Number: 
- Closes #242 
- Closes #276 
Fixing bugs
> Bridge deposit Currency/chains mismatching & PolkadotTx notification duplicates fixes

- packages/apps/src/initI18n.ts
- packages/react-environment/src/WebbProvider.tsx
- packages/react-environment/src/api-providers/polkadot/polkadot-mixer-withdraw.ts
- packages/react-environment/src/api-providers/polkadot/polkadot-transaction.ts
- packages/react-environment/src/api-providers/polkadot/webb-polkadot-provider.ts
- packages/react-environment/src/api-providers/web3/web3-bridge-deposit.ts
- packages/react-environment/src/api-providers/web3/web3-bridge-withdraw.ts
- packages/react-environment/src/api-providers/web3/web3-mixer-deposit.ts
- packages/react-environment/src/api-providers/web3/web3-mixer-withdraw.ts
- packages/react-environment/src/api-providers/web3/web3-wrap-unwrap.ts
- packages/react-environment/src/api-providers/web3/webb-web3-provider.ts
- packages/react-environment/src/webb-context/webb-provider.interface.ts
- packages/wallet/src/providers/polkadot/polkadot-provider.ts
- packages/wallet/src/providers/polkadot/transaction-notification-config.tsx
`NotificaitonApi` and `TransactionConfig` are used across the providers
Issue Number: Closes #331 
```
// Function call to register a notification
export type NotificationHandler = ((notification: NotificationPayload) => string | number) & {
// remove the notification programmatically
remove(key: string | number): void;
}
```
Added this interface to the provider will make it easer to control the behavior of ht notification
> Linking the notification API/TX notification config to the provider

- README.md
- Mentions external how to guide for local mixer setup
> chore: mention external how to guide for local mixer setup

- packages/bridge/package.json
- packages/bridge/src/components/DepositConfirm/DepositConfirm.tsx
- packages/mixer/package.json
- packages/mixer/src/components/Deposit/Deposit.tsx
- packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
- packages/react-components/package.json
- packages/react-hooks/package.json
- packages/react-hooks/src/index.ts
- packages/react-hooks/src/useCopyable.ts
- packages/ui-components/package.json
- packages/ui-components/src/Inputs/MixerGroupSelect/MixerGroupSelect.tsx
- packages/ui-components/src/Inputs/WalletSelect/WalletDetails.tsx
- packages/vbridge/package.json
- packages/vbridge/src/components/DepositConfirm/DepositConfirm.tsx
- yarn.lock
- feat: add copyable hook for reusable
- feat: add tooltip for copy address button
Issue Number: Closes #370 
Thank you @dutterbutter for the comprehensive description in the [issue](https://github.com/webb-tools/webb-dapp/issues/370) 😇.
> Add tooltip for copy address button

- packages/apps/src/configs/logos/chains/ArbitrumLogo.tsx
- packages/mixer/src/hooks/note/index.ts
- packages/page-wrap-unwrap/src/index.tsx
- packages/react-components/src/InteractiveFeedbackView/DefaultErrorView.tsx
- packages/react-components/src/InteractiveFeedbackView/UnselectedNetworkView.tsx
- packages/react-environment/src/WebbProvider.tsx
- packages/react-environment/src/error/interactive-errors/extension-not-installed.tsx
- packages/react-hooks/src/currency/useNativeCurrencyBalance.tsx
- packages/react-hooks/src/useWallets.ts
- packages/ui-components/src/Inputs/AmountInput/AmountInput.tsx
- packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
- packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
- packages/ui-components/src/Tabs/MixerTabs.tsx
- packages/ui-components/src/styling/themes/makeTheme.ts
Warning logs and errors logs pollute the console.
Issue Number: Closes #243 
Resolve as much as possible logs occurs in browser.
Don't have
> Fix and remove logs / errors in browser console

- packages/page-crowdloan/src/hooks/useCrowdloan.ts
- packages/page-crowdloan/src/index.tsx
- packages/react-environment/src/WebbProvider.tsx
- packages/ui-components/src/Buttons/MixerButton.tsx
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
- feat: require connect to kusama chain before contribute
- style: the chain button when loading for consistent ui
- style: add wrapper component for checbox section to consistent padding
User navigates to crowdloan page, the wallet previously connected remains and no informative message is provided to the user.
Issue Number: https://github.com/webb-tools/webb-dapp/issues/428
https://user-images.githubusercontent.com/60747384/174670359-485111a7-61b4-4a35-8cc5-46a2485002dc.mp4
This is a simple and fast delivery solution. Feel free to comment or request a change if you think that would help the UI/UX better.
@dutterbutter @drewstone
> Inform user to switch to Kusama chain in Crowdloan page

- packages/react-components/src/Withdraw/WithdrawingModal.tsx
- packages/ui-components/package.json
- packages/ui-components/src/Chip/Chip.tsx
- packages/ui-components/src/Chip/index.ts
- packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
- packages/ui-components/src/Inputs/ChainSelection/ChainSelection.tsx
- packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
- packages/ui-components/src/Inputs/TokenSelection/TokenSelection.tsx
- packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
- packages/ui-components/src/Inputs/shared/ListEmpty/ListEmpty.tsx
- packages/ui-components/src/Inputs/shared/ListEmpty/index.ts
- packages/ui-components/src/Inputs/shared/ListEmpty/styled/ListEmptyWrapper.tsx
- packages/ui-components/src/Inputs/shared/ListEmpty/styled/index.ts
- packages/ui-components/src/Inputs/shared/index.ts
- packages/ui-components/src/Inputs/shared/styled/index.ts
- packages/ui-components/src/Inputs/shared/styled/selections-modal/CircleStatus.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/CloseHeaderButtonWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/ItemWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/ListWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/SearchIconWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/SearchWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/SelectionWrapper.tsx
- packages/ui-components/src/Inputs/shared/styled/selections-modal/index.ts
- packages/ui-components/src/Modal/Modal.tsx
- packages/ui-components/src/NetworkManger/NetworkManager.tsx
- packages/ui-components/src/NetworkManger/NetworkManagerIndicator.tsx
- packages/ui-components/src/index.ts
- packages/ui-components/src/utils/index.ts
- yarn.lock
- chore: create common styled components for selection list
- feat: add empty list component for empty state
- feat: allow modal to stay center in the screen
- refactor: applied the common styled components and remove duplicate code.
- chore: add border for header buttons in dark mode
- refactor: update rounded amount function for better approximate
- refactor: `NetworkManagerIndicator` component to separate file.
- feat: add `Chip` component
- chore: use `Chip` component to display status on modal
- chore: change label in mixer withdraw modal to `Mixer info`
- fix: update empty icon color
- The size of chain and token selection modals is overflow on the large screen …
> Improve UI components

- packages/mixer/src/components/Withdraw/Withdraw.tsx
> Add onclick function to mixer relayer modal button

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
Changes introduced in this pr:
- updates pr template 
- add codeowners for auto review
> chore: update pr template and add codeowners

- packages/api-providers/src/polkadot/anchor-api.ts
- packages/api-providers/src/polkadot/chain-query.ts
- packages/react-environment/src/WebbProvider.tsx
- packages/ui-components/src/utils/index.ts
- packages/vbridge/src/components/Deposit/Deposit.tsx
Issue Number: Closes #468  #472 
- Disable the Deposit button on insufficient balance
- Display the right amount on the Balance label (Finx Rounding up)
- Fix unimplemented substrate balance query 
https://user-images.githubusercontent.com/35463181/182342468-fb616553-5008-448c-a687-b634d61c2565.mp4
> Fix balance display and disable the deposit button

- packages/api-providers/src/web3/webb-provider.ts
- packages/react-environment/src/WebbProvider.tsx
Duplicate notifications appeared for web3 provider
Issue Number: Closes #444 
The notification shows now only once
https://user-images.githubusercontent.com/35463181/182423195-b2852fa0-6543-49c3-b6b4-79ab84aa449f.mp4
> Fix duplicate notifications

- packages/react-hooks/src/currency/useCurrencies.tsx
- packages/react-hooks/src/currency/useCurrencyBalance.tsx
- chore: remove logs
- fix: add missing dependencies for balance label
- Remove logs
- Display and sync the balance label properly when switching accounts or networks
- Closes https://github.com/webb-tools/webb-dapp/issues/474
-----
https://user-images.githubusercontent.com/60747384/183943720-66902d8c-6b61-4412-8e70-0353337d6025.mp4
> Fix balance label

- packages/api-providers/src/abstracts/anchor/vanchor-registration.ts
- packages/api-providers/src/abstracts/webb-provider.interface.ts
- packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
- packages/api-providers/src/notes/note-manager.ts
- packages/api-providers/src/polkadot/chain-query.ts
- packages/api-providers/src/polkadot/vanchor-registration.ts
- packages/api-providers/src/polkadot/webb-provider.ts
- packages/api-providers/src/utils/storage.ts
- packages/api-providers/src/web3/vanchor-deposit.ts
- packages/api-providers/src/web3/vanchor-registration.ts
- packages/api-providers/src/web3/webb-provider.ts
- packages/api-providers/src/web3/wrap-unwrap.ts
- packages/react-components/src/NoteAccount/NoteAccountDetails.tsx
- packages/react-components/src/PermissionedAccess/CreateNoteAccount.tsx
- packages/react-components/src/PermissionedAccess/RequiredNoteAccount.tsx
- packages/vbridge/src/VBridge.tsx
- packages/vbridge/src/components/Deposit/Deposit.tsx
- packages/vbridge/src/components/Withdraw/Withdraw.tsx
- packages/vbridge/src/hooks/deposit/useBridgeDeposit.tsx
- Require a NoteAccount to complete the Deposit flow on the DApp.
- Enable a button for 'Connecting With Metamask'.
-----
https://user-images.githubusercontent.com/16654909/185417806-813d259c-56eb-4c73-9ecd-a4bef0a108a4.mov
> Register accounts on deposit and enable registration with MetaMask.

- packages/api-providers/src/polkadot/transaction.ts
> UI bug Fixes, and fix tangle token

- packages/webb-ui-components/src/components/Chip/Chip.tsx
- packages/webb-ui-components/src/components/Chip/index.ts
- packages/webb-ui-components/src/components/Chip/types.d.ts
- packages/webb-ui-components/src/components/Chip/utils.ts
- packages/webb-ui-components/src/components/index.ts
- packages/webb-ui-components/src/types/index.d.ts
- Add a new `Chip` component
- Closes https://github.com/webb-tools/webb-dapp/issues/509
-----
> New Chip component

- packages/mixer/src/Mixer.tsx
- packages/ui-components/src/styles/global.tsx
- packages/webb-ui-components/package.json
- packages/webb-ui-components/src/components/Slider/Slider.tsx
- packages/webb-ui-components/src/components/Slider/index.ts
- packages/webb-ui-components/src/components/Slider/types.d.ts
- packages/webb-ui-components/src/components/index.ts
- yarn.lock
- feat: add new `Slider` component
- Added new `Slider` component
- Closes https://github.com/webb-tools/webb-dapp/issues/512
-----
> New `Slider` Component

- packages/mixer/src/Mixer.tsx
- packages/webb-ui-components/package.json
- packages/webb-ui-components/src/components/Button/utils.ts
- packages/webb-ui-components/src/components/Chip/Chip.tsx
- packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
- packages/webb-ui-components/src/components/Tooltip/index.ts
- packages/webb-ui-components/src/components/Tooltip/types.d.ts
- packages/webb-ui-components/src/components/index.ts
- yarn.lock
- refactor: add `forwardRef` for `Chip` component
- fix: uncorrect button size
- feat: add new `Tooltip` component
- chore: make use of new `Tooltip` component
- doc: add component document
- Add `forwardRef` to `Chip` component
- Fix incorrect button size
- Added new `Tooltip` component
- Closes https://github.com/webb-tools/webb-dapp/issues/513
-----
> Add `Tooltip` Component

- graphql.schema.json
- packages/page-statistics/README.md
- packages/page-statistics/src/AuthoritiesData.tsx
- packages/page-statistics/src/generated/graphql.tsx
- packages/page-statistics/src/gql/metadata.graphql
- packages/page-statistics/src/gql/proposals.graphql
- packages/page-statistics/src/gql/public-keys.graphql
- packages/page-statistics/src/gql/sessions.graphql
- packages/page-statistics/src/provider/DemoTable.tsx
- packages/page-statistics/src/provider/hooks/index.ts
- packages/page-statistics/src/provider/hooks/types.ts
- packages/page-statistics/src/provider/hooks/useAuthorities.ts
- packages/page-statistics/src/provider/hooks/useCurrentMetaData.ts
- packages/page-statistics/src/provider/hooks/useKeys.ts
- packages/page-statistics/src/provider/hooks/useProposal.ts
- schema.graphql
- scaffolding statistics API integration with the dApp
- Wrapped the key UI backend
- Closes #564 
- Closes #567 
-----
> Keys Stats API

- netlify.toml
- Adds deployment config file for build
- Closes 
-----
> chore: deployment file for stats

- packages/page-statistics/src/App.tsx
- Check if the dApp is running on the dev mode and add the url for the deplyed or local subquery node
- Closes 
-----
> Added the deployed node URI for deployed stats

- packages/page-statistics/src/App.tsx
- Updates subql deployment link
- Closes 
-----
> chore: update link

- apps/bridge-dapp/src/App.tsx
- apps/bridge-dapp/src/components/Header/Header.tsx
- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/hooks/index.ts
- apps/bridge-dapp/src/hooks/useConnectWallet.ts
- libs/api-provider-environment/src/WebbProvider.tsx
- libs/api-provider-environment/src/app-event/app-events.class.ts
- libs/api-provider-environment/src/webb-context/webb-context.ts
- libs/dapp-config/src/wallets/wallet-config.interface.ts
- libs/dapp-config/src/wallets/wallets-config.tsx
- libs/webb-ui-components/src/components/Modal/ModalContent.tsx
- libs/webb-ui-components/src/components/Modal/types.d.ts
- libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
- libs/webb-ui-components/src/components/WalletConnectionCard/types.ts
⚠️ This PR still working in progress, the current flow is incorrect and needs to update. It's waiting for the conditional rendering setup to be done. But the PR contains helpful resources for referencing the logic and the UI implementation.
- Fix icons and add Modal component (#672)
- Update the DepositCard inputs to read and modify api-provider state
- Fix dest chain to use typed chain id
- feat: add logic for wallet connection button
- style buttons when wallet is connected
- Add logic for wallet connect button on header
- Closes `NaN`
-----
https://user-images.githubusercontent.com/60747384/199559543-26c9e745-825b-4230-869b-9619243125f0.mp4
> Wallet Connect Button on Header

- libs/webb-ui-components/package.json
- libs/webb-ui-components/src/components/Accordion/Accordion.tsx
- libs/webb-ui-components/src/components/Accordion/AccordionButton.tsx
- libs/webb-ui-components/src/components/Accordion/AccordionContent.tsx
- libs/webb-ui-components/src/components/Accordion/AccordionItem.tsx
- libs/webb-ui-components/src/components/Accordion/index.ts
- libs/webb-ui-components/src/components/Accordion/types.ts
- libs/webb-ui-components/src/components/index.ts
- libs/webb-ui-components/src/stories/molecules/Accordion.stories.jsx
- yarn.lock
- Added the accordion component to the UI 
- Closes #676 
-----
> Implemented the accordion component

- apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
- Fix #698 
- Closes #698
-----
> Fix proposal details overflow

- .github/CODEOWNERS
- Updates to codeowners file
- Closes 
-----
> chore: update to codeowners file

- apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
- libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
- libs/webb-ui-components/src/components/ChainsRing/index.ts
- libs/webb-ui-components/src/components/ChainsRing/types.d.ts
- libs/webb-ui-components/src/components/index.ts
- libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
- libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
- libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
- libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
- Update the tokens ring component to the chains ring component
- An applied new component to deposit, withdraw and transfer confirm components
- Closes https://github.com/webb-tools/webb-dapp/issues/679
-----
> Chain rings component

- apps/stats-dapp/src/components/Header/Header.tsx
- libs/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
- libs/webb-ui-components/src/components/MenuItem/MenuItem.tsx
- libs/webb-ui-components/src/components/ThemeSwitcher/ThemeSwitcherButton.tsx
- libs/webb-ui-components/src/constants/index.ts
- In header, Tangle Explorer button is now changed to Webb App button
- Dark/Light toggle is moved to top navigation header
- Header dropdown design is updated to match with updated design
- Header dropdown now emphasizes custom data source input
- Closes #743
- Closes #744
> Header dropdown design update

- libs/webb-ui-components/src/constants/index.ts
- Changes Webb App to Minerva Bridge in header
- Updates the Minerva Bridge link
> Updates webb app name and link

- apps/stats-dapp/src/components/Header/Header.tsx
- apps/stats-dapp/src/routes/index.tsx
- libs/webb-ui-components/src/constants/index.ts
- Header navigation tabs reflects the proposed design
- Keys page is now the landing page
- Closes #751
> Header navigation tabs reflects proposed design

- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/DepositContainer/types.d.ts
- apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
- apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/types.d.ts
- apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
- apps/bridge-dapp/src/containers/SpendNotesTableContainer/types.d.ts
- apps/bridge-dapp/src/containers/TransferContainer/types.d.ts
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
- apps/bridge-dapp/src/containers/types.d.ts
- apps/bridge-dapp/src/hooks/useShieldedAssets.ts
- apps/bridge-dapp/src/hooks/useSpendNotes.ts
- apps/bridge-dapp/src/pages/PageBridge.tsx
- libs/responsive-utils/src/layout/use-dimensions.hook.ts
- libs/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
- libs/webb-ui-components/src/components/BridgeInputs/types.ts
- libs/webb-ui-components/src/containers/DepositCard/types.ts
- Add deposit, withdraw and transfer functions when a user hits the action buttons on the shielded asset table
- Add withdraw and transfer functions when a user chooses withdraw or transfer on the spend note table
- Add smoothScroolToTop function to support scroll to top effect.
- Closes https://github.com/webb-tools/webb-dapp/issues/739
- Closes https://github.com/webb-tools/webb-dapp/issues/738
- Closes https://github.com/webb-tools/webb-dapp/issues/737
- Closes https://github.com/webb-tools/webb-dapp/issues/736
- Closes https://github.com/webb-tools/webb-dapp/issues/735
-----
https://user-images.githubusercontent.com/60747384/205048358-011d5cd9-f83c-4b4d-b689-88419d4c05b6.mp4
> Setup Note Account Tables Actions

- apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
- Fixes deposit casing card title
- Closes 
-----
> chore: fix card casing

- apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
- apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
- adds tooltip for keygen threshold column header
- centers column data in keygen table
> Adds tooltip for keygen threshold column header

- apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
- Updates copy for note account dialogue box
- Closes #709 
-----
> chore: update account dialogue copy

- .github/CODEOWNERS
- Adds pavan to codeowners 
- Closes 
-----
> chore: add Pavan to codeowners

- libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
- Changes deposit to to destination chain 
- Closes #822 
-----
> chore: updates deposit label

- README.md
- Fix readme badge
- Closes 
-----
> chore: fix readme badge

- apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
- Adds chain name and logo in proposal details page.
- Closes #686
> Adds chain name and logo in proposal details page

- .github/CODE_OF_CONDUCT.md
- .github/workflows/landing-page-dapp-dev.yml
- apps/webbsite/next.config.js
- apps/webbsite/src/components/sections/PrivacyConnectedSection.tsx
- apps/webbsite/src/pages/_app.tsx
- package.json
- Deploys webbsite to netlify for development purposes 
- Adds github workflow for webbsite
- Adds code of conduct 
To preview:
- https://webbsite-dev.netlify.app/
Tasks Remaining for Webb marketing site:
- https://github.com/webb-tools/webb-dapp/issues/766
- Closes 
-----
> chore: test deployment pipeline for webbsite

- apps/bridge-dapp/src/components/Header/Header.tsx
- apps/bridge-dapp/src/components/Header/WalletButton.tsx
- apps/bridge-dapp/src/components/Header/WalletModal.tsx
- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/hooks/useConnectWallet.ts
- apps/bridge-dapp/src/react-app-env.d.ts
- apps/bridge-dapp/src/utils/getDefaultConnection.ts
- apps/bridge-dapp/src/utils/index.ts
- libs/abstract-api-provider/src/webb-provider.interface.ts
- libs/api-provider-environment/src/WebbProvider.tsx
- libs/browser-utils/src/platform/get-platform-metadata.ts
- libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
- Chain selection card is opened every time upon clicking the connect button. 
- Closes #819 
https://user-images.githubusercontent.com/53374218/208578453-56a0d0d7-ab44-4b01-8d54-df31f0c2467a.mov
> Connect button opens chain selection card

- libs/webb-ui-components/src/constants/index.ts
- change bridge name in stats dApp
- Closes 
-----
> chore: change bridge name in stats dApp

- .storybook/main.js
- apps/bridge-dapp/src/utils/index.ts
- apps/stats-dapp/src/generated/graphql.tsx
- libs/webb-ui-components/src/constants/index.ts
- package.json
- Adds back storybook accessibility review features
- `yarn nx build-storybook webb-ui-components`: Build storybook
- `yarn nx storybook webb-ui-components`: Serve storybook for development
- Closes 
-----
> chore: add back accessibility for storybook

- .github/workflows/deploy-bridge-dapp-dev.yml
- .github/workflows/deploy-stats-dapp-dev.yml
- We have moved to an oss sponsored netlify acct so this pr reflects those changes
- Closes 
-----
> chore: update deployment workflows for new netlify acct

- libs/webb-ui-components/src/components/Button/utils.ts
- Updates dark mode buttons to have a white background.
- Closes #890 
https://user-images.githubusercontent.com/53374218/212431847-874b1309-5431-474a-8dc5-b41dae947b4e.mov
> Updates dark mode buttons to have a white background

- apps/bridge-dapp/src/components/Header/ChainSwitcherButton.tsx
- apps/bridge-dapp/src/components/Header/Header.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
- libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
- libs/webb-ui-components/src/components/ListCard/WithdrawListCard.tsx
- libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
- Address case discrepancies
- Select Token -> Select token
- Select Chain -> Select chain 
- Connect Wallet -> Connect wallet
- Select Bridging Asset -> Select bridging asset
- Closes 
-----
> chore: fix type cases

- apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
- apps/bridge-dapp/src/pages/PageBridge.tsx
- libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
- libs/webb-ui-components/src/components/BridgeInputs/types.ts
- libs/webb-ui-components/src/components/Input/Input.tsx
- libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
- libs/webb-ui-components/src/components/TokenWithAmount/TokenWithAmount.tsx
- libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionCardFooter.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/types.ts
- Removes usage of `.txt` file extension to download notes.
- Deposit flow UI changes updated to align with the design.
- Fixed multiple external link issue in transaction status in transaction processing component.
- Download All now downloads the notes.
- Increases text font size in transaction processing component.
https://www.loom.com/share/c38a1f72c3c24441b55a5ea26404c286
- Closes #899 
- Closes #858 
- Closes #860 
- Closes #884 
- Closes #896
> UI bug fixes bridge

- apps/bridge-dapp/src/components/Header/ChainSwitcherButton.tsx
- apps/bridge-dapp/src/components/Header/Header.tsx
- apps/bridge-dapp/src/components/Header/WalletModal.tsx
- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
- libs/webb-ui-components/src/components/ListCard/types.ts
- Chain selection component now shows connected label when opened through chain switcher button.
https://user-images.githubusercontent.com/53374218/213808447-c1662fe2-b3b0-4825-a0f3-69acb066d167.mov
- Closes #697
> Fixes connected label in chain selection component

- README.md
- apps/bridge-dapp/webpack.serve.js
- package.json
- Fixes twitter badge based on API changes mentioned here: https://github.com/badges/shields/issues/8837
- Closes 
-----
> chore: update readme

- apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
- apps/bridge-dapp/src/utils/getTokenURI.ts
- apps/bridge-dapp/src/utils/index.ts
- libs/abstract-api-provider/src/transaction.ts
- libs/abstract-api-provider/src/webb-provider.interface.ts
- libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
- libs/polkadot-api-provider/src/webb-provider.ts
- libs/react-hooks/src/currency/useCurrenciesBalances.tsx
- libs/web3-api-provider/src/webb-provider.ts
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
- libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
- libs/webb-ui-components/src/containers/TransactionProgressCard/types.ts
https://user-images.githubusercontent.com/53374218/214838046-2bac8f16-fac0-4cee-94a4-736f2a2fc890.mov
https://user-images.githubusercontent.com/53374218/214868986-c420429e-6d21-4349-a7cc-2ad7fa5bac45.mov
- Closes #900 
- Closes #870
> Fixes dead link in transaction processing component

- apps/bridge-dapp/src/components/Header/WalletButton.tsx
- libs/icons/src/wallets/MetaMaskIcon.tsx
- libs/webb-ui-components/src/components/Button/Button.tsx
- libs/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
- libs/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
- libs/webb-ui-components/src/typography/utils/index.ts
Wallet button in header dropdown is updated to align with the latest design update.
https://user-images.githubusercontent.com/53374218/214576514-db6173e0-e533-4bcd-af9a-dcca77d98209.mov
https://user-images.githubusercontent.com/53374218/214576899-1f0ecb18-e27d-4274-96cd-c7551c4b76d0.mov
- Closes #892
> Wallet button UI changes

- libs/webb-ui-components/src/css/layer-components.css
- Updates h5 font size and line height.
- Closes #929
> Updates h5 font size and line height

- apps/bridge-dapp/src/components/tables/EmptyTable.tsx
- apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
- apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
- apps/bridge-dapp/src/pages/PageBridge.tsx
- Updates no spend notes available message
- Fixes Upload spend notes dead link  
https://user-images.githubusercontent.com/53374218/215608682-2b194db4-4122-4d34-9162-d414b26e50a7.mov
- Closes #942
> Fixes upload spend note dead link and no spend note message

- apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx
- Catches invalid note upload error and notifies the user about the invalid note upload.
- Closes #941 
https://user-images.githubusercontent.com/53374218/216020524-14d4ccd0-36df-4d7c-92a1-cb6f7e99d997.mov
-----
> fixes invalid note upload error

- apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
- libs/webb-ui-components/src/components/Slider/Slider.tsx
- Fixes stats dApp filter slider error.
- Closes #684 
- Closes #687 
https://user-images.githubusercontent.com/53374218/216034712-3f1eb4cf-a55d-45c9-9e7c-c4608773e248.mov
-----
> Fixes stats slider error

- apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
- apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
- apps/stats-dapp/src/pages/Keys.tsx
- Fixes keys page flicker issue
- Closes #910 
https://user-images.githubusercontent.com/53374218/216340029-369b314e-e483-46d5-9838-3ac3f340645a.mov
-----
> Fixes keys page flicker issue

- apps/bridge-dapp/src/components/Header/Header.tsx
- Updates navigation bar dimensions to `1160 x 40`.
- Closes #976 
https://user-images.githubusercontent.com/53374218/216374832-bdf5542f-4ae7-4a24-89f7-3b9e0aac080d.mov
-----
> Updates navigation bar max width

- apps/webbsite/src/components/sections/HeroSection.tsx
- apps/webbsite/src/components/sections/ResearchAndDevelopmentSection.tsx
- Fixes outdated links from new docs deployment
- Closes 
-----
> chore: fix outdated links

- apps/webbsite/src/components/Navbar.tsx
- apps/webbsite/src/constants/index.ts
- Adds docs link in navbar.
https://user-images.githubusercontent.com/53374218/217359618-ff8db75d-7735-403d-bb8d-65e0f12cab71.mov
> Adds docs link in navbar

- apps/stats-dapp/src/provider/hooks/useKeys.ts
- update timestamp for stats to reflect 6 hours
- Closes 
-----
> chore: update timestamp for stats to reflect 6 hours

- apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
- apps/bridge-dapp/src/components/EducationCard/types.d.ts
- apps/bridge-dapp/src/pages/PageBridge.tsx
- Change the Education Card based on the status of the transaction queue card
- Closes `NaN`
> Open and Close Education Card

- apps/webbsite/src/pages/_app.tsx
- adds plausible script to marketing site
- Closes 
-----
> chore: add plausible script to marketing site

- apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- apps/bridge-dapp/src/hooks/useEducationCardStep.ts
- libs/relayer-manager-factory/src/relayer-manager-factory.ts
- package.json
- yarn.lock
- feat: add education card step hook to manage the step
- feat: add logic for setting education card step on deposit flow
- chore: update education step corresponding to the user's input
- Added `use-observable-hooks` lib to allow creating the sharable state with `Rx.js` in hooks
- Added `useEducationCardStep` hook
- Added side effects on the `deposit`, `transfer`, and `withdraw` tabs to set the education card step
- Closes `NaN`
https://user-images.githubusercontent.com/60747384/221374417-8f3bb305-aa5b-4e52-a7af-a989ae68b2d5.mp4
-----
_Please be sure to add …
> Dynamic Education Card Step

- libs/web3-api-provider/src/webb-provider.ts
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- Padded UTXOs before calling `setupTransaction` method.
- Closes `NaN`
https://user-images.githubusercontent.com/60747384/222533527-96f60f8d-b5c9-4cc5-9803-2d7abd07c91b.mp4
> Pad UTXO Before calling setupTransaction

- apps/bridge-dapp/src/components/Header/Header.tsx
- libs/note-manager/src/note-manager.ts
- libs/web3-api-provider/src/webb-provider.ts
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- Removing local storage when user clears the note
- Passing the index when generating the note
- Use `||` for fallback block number value 
- Add `leafIndex` validation when the commitment is not in the tree
- Closes `NaN`
> Fix Withdraw Issue

- .github/workflows/check-build.yml
- .github/workflows/check-lint.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/pr-reviewer.yml
- Adds an auto review bot
- Closes 
-----
> chore: trial auto-reviewer bot

- .github/workflows/release.yml
- apps/bridge-dapp/CHANGELOG.md
- apps/stats-dapp/CHANGELOG.md
- Quick fix for release deployment flow
- Closes 
-----
> [RELEASE] - fix: hubble-v.0.02 and stats-dapp-v0.0.2

- apps/faucet/src/pages/index.tsx
> minor adjustment for the main card in faucet website

- apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
- Updates proposal chart to show data from first available data point.
> Updates proposal chart to show data from first available data point

- apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
- apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
- apps/stats-dapp/src/pages/Proposals.tsx
- apps/stats-dapp/src/provider/hooks/useProposals.ts
- apps/stats-dapp/src/utils/mapChainIdToCurrencyName.ts
- libs/icons/src/utils.ts
- Removes `txn hash` column and it's references everywhere from stats dapp.
- Fixes `prev` and `next` button not working in proposal details page.
- Removes open governance chip from proposal details page.
- Updates webb chain logo to tangle logo in proposal table.
> Update/fix stats-dapp UI discrepancies Part 1

- apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
- libs/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
- Updates proposal timeline to display correct timeline status.
- Updates timeline date & time format.
-----
> Fixes Proposal Timeline

- apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
- apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
- apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
- apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
- libs/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
- libs/webb-ui-components/src/components/Filter/Filter.tsx
- libs/webb-ui-components/src/components/Input/Input.tsx
- Fixes UI typescale: filter, custom data source input, back button on detail pages, proposal detail in detail page.
- Fixes not displaying removed proposal status in proposals table.
> Stats Improvements and Fixes

- apps/stats-dapp/src/containers/Layout/Layout.tsx
- apps/stats-dapp/src/index.tsx
- apps/stats-dapp/src/styles.css
- apps/stats-dapp/styles.css
- libs/webb-ui-components/src/components/Footer/Footer.tsx
- Adds the new swirl BG image (includes tangle token) to stats dapp.
> Adds swirl BG image to stats dapp

- libs/webb-ui-components/src/constants/index.ts
- Fixes incorrect link
- Closes 
-----
> Fix bridge link

- apps/webbsite/src/pages/404.tsx
Update the Explore the Blog button to Get Help Button with Discord link
Closes #1272 
Closes #1252 
https://github.com/webb-tools/webb-dapp/assets/69841784/8ad9c03e-777f-4c31-9203-6296273ed1bd
-----
> Update GetHelp Button

- libs/dapp-config/src/anchors/anchor-config.ts
- Update new VAnchor addresses of new Orbit deployment.
> Update new Orbit Deployment

- apps/tangle-website/src/components/sections/CommunitySection.tsx
- libs/icons/src/SparklingIcon.tsx
- libs/icons/src/index.ts
- libs/webb-ui-components/src/components/WebsiteCommunity/WebsiteCommunity.tsx
- libs/webb-ui-components/src/components/WebsiteCommunity/types.ts
Add Incentivized Testnet item in Community Section
Closes #1271  
Uploading Screen Recording 2023-05-30 at 11.50.09.mov…
-----
> Add Incentivized Testnet item in Community Section

- apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
- Removes graph gradient colors.
- Legend now shows available proposal types only.
> Remove graph gradient colors and updates legend

- apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
- yarn.lock
- Fix the proposal page crashes due to resolve conflict and using the unsupported time range.
> [Hot Fix] Stats Proposal Page Crashes

- apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
- apps/stats-dapp/src/pages/Proposals.tsx
- Proposal table pagination now does not refresh the whole page.
- Closes #1296 
https://github.com/webb-tools/webb-dapp/assets/53374218/9a15051f-abc1-43ba-9dca-062be6092697
> Fixes proposal table buggy pagination

- libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
Fix Footer Spacing in marketing sites.
- Closes #1246 
https://github.com/webb-tools/webb-dapp/assets/69841784/9aef323b-337e-49a8-82f5-f8cfc55654e8
-----
> Remove bottom padding in footer

- apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/shared.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
- Adds estimated transaction fee tooltip.
- Closes #1256
> Adds estimated transaction fee tooltip

- apps/faucet/src/components/Header.tsx
- apps/faucet/src/pages/index.tsx
- libs/dapp-config/src/links.ts
> Update copy - closes #1323

- .lycheeignore
- apps/bridge-dapp/CHANGELOG.md
- apps/bridge-dapp/package.json
- apps/bridge-dapp/src/containers/Layout/Layout.tsx
- apps/bridge-dapp/src/pages/PageBridge.tsx
- apps/faucet/CHANGELOG.md
- apps/faucet/package.json
- apps/faucet/src/pages/index.tsx
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
- apps/tangle-website/CHANGELOG.md
- apps/tangle-website/package.json
- apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
- apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
- apps/tangle-website/src/components/sections/SupportedBySection.tsx
- apps/webbsite/CHANGELOG.md
- apps/webbsite/package.json
- libs/webb-ui-components/src/constants/index.ts
- libs/webb-ui-components/src/css/layer-components.css
- Bridge dApp `v0.0.11`
- Faucet dApp `v0.0.4`
- Stats dApp `v0.0.10`
- Tangle website `v.0.0.4`
- Webbsite `v.0.0.4`
> [RELEASE] Release dApps `2023-06-09`

- apps/bridge-dapp/src/components/Header/Header.tsx
- Fixes bridge header component
> Fixes bridge header component

- apps/bridge-dapp/src/components/Header/Header.tsx
- Fixes wallet connect loading state
> Fixes wallet connect loading state

- apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
- apps/stats-dapp/src/provider/hooks/mappers/index.ts
- apps/stats-dapp/src/provider/hooks/useKeys.ts
- Fixes stats keys table pagination issue.
- Closes #1336 
https://github.com/webb-tools/webb-dapp/assets/53374218/67e0fd97-3704-4179-a8c1-f63c07b40c8c
> Fixes stats keys table pagination

- apps/tangle-website/src/components/LinkButton.tsx
- apps/tangle-website/src/components/Navbar.tsx
- apps/tangle-website/src/components/leaderboard/CountdownSection.tsx
- apps/tangle-website/src/components/sections/FeaturesSection.tsx
- apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
- apps/tangle-website/src/components/sections/HeroSection.tsx
- apps/tangle-website/src/components/sections/SupportedBySection.tsx
- apps/tangle-website/src/components/sections/UseCasesSection.tsx
- apps/tangle-website/src/styles/globals.css
Fix button line in small screens on marketing sites
- Closes #1340 
https://github.com/webb-tools/webb-dapp/assets/69841784/3c4e6e38-e976-41a0-9043-d12129604d67
-----
> fix button line in small screen

- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- Closes confirm containers when the txn is dismissed.
- Closes #1189 
https://github.com/webb-tools/webb-dapp/assets/53374218/430fd4c3-b0bb-413e-ba9c-68ec5827ef5b
> Close confirm containers when txn is dismissed

- apps/faucet/src/components/Header.tsx
- apps/tangle-website/src/pages/_app.tsx
- apps/tangle-website/src/pages/privacy-policy.tsx
- apps/tangle-website/src/pages/terms-and-conditions.tsx
- apps/tangle-website/src/styles/globals.css
- libs/dapp-config/src/links.ts
Add styling to Privacy Policy and Terms Conditions pages of the Tangle Website
- Closes #1369 
https://github.com/webb-tools/webb-dapp/assets/69841784/3fc2142f-ce46-4f9c-8337-0db9a4ed92ad
-----
> Privacy Policy and Terms Conditions pages for the Tangle Website

- .lycheeignore
- apps/bridge-dapp/CHANGELOG.md
- apps/bridge-dapp/package.json
- apps/faucet/CHANGELOG.md
- apps/faucet/package.json
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
- apps/tangle-website/CHANGELOG.md
- apps/tangle-website/package.json
- apps/webbsite/CHANGELOG.md
- apps/webbsite/package.json
- Add token to wallet ([#1341](https://github.com/webb-tools/webb-dapp/pull/1341))
- Optimize fetching contracts data ([#1350](https://github.com/webb-tools/webb-dapp/pull/1350))
- Add Faucet link in navigation menu ([#1350](https://github.com/webb-tools/webb-dapp/pull/1355))
- Utilize Circom Proving for Substrate, Centralized the shared types, Move fetchOnChainConfig logic into webpack ([#1361](https://github.com/webb-tools/webb-dapp/pull/1361))
- Close confirm containers when txn is dismissed ([#1362](https://github.com/webb-tools/webb-dapp/pull/1362))
- Removes extra bg image on bridge ([#1367](https://github.com/webb-tools/webb-dapp/pull/1367))
- Fixes stats keys table pagination ([#1338](https://github.com/webb-tools/webb-dapp/pull/1338))
- Fixes stats progress bar session length …
> [RELEASE] - Release dApps `2023-06-28`

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/deploy-hubble-stats.yml
- .github/workflows/release.yml
- Adding GA workflows for the `hubble-stats` dapp.
> Adding GA workflow for hubble-stats dapp

- .github/dependabot.yml
> Add `dependabot`

- apps/tangle-website/src/styles/globals.css
- apps/webbsite/src/pages/privacy-policy.tsx
- apps/webbsite/src/styles/globals.css
- Enhance formatting of Privacy Policy Page on marketing sites
- Closes #1443 
https://github.com/webb-tools/webb-dapp/assets/69841784/4c113af8-29fe-4358-8688-dd20da2ef207
https://github.com/webb-tools/webb-dapp/assets/69841784/b9f330b5-172c-4282-b2ce-d82818e3ea2d
-----
> chore: update privacy & policy page in mkt sites based on latest design

- apps/faucet/CHANGELOG.md
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/src/containers/Layout/Layout.tsx
- apps/tangle-website/CHANGELOG.md
- apps/webbsite/CHANGELOG.md
- Hot fix the fixed height on stats dapp.
- Add small modifications to the apps to trigger previous failed releases.
> [RELEASE] Hot Fix the Fixed Height on Stats dApp

- apps/hubble-stats/app/page.tsx
- apps/hubble-stats/app/pool/[slug]/page.tsx
- apps/hubble-stats/components/BarChart/BarChart.tsx
- apps/hubble-stats/components/BarChart/types.ts
- apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
- apps/hubble-stats/components/Breadcrumbs/types.ts
- apps/hubble-stats/components/NetworkPoolTable/NetworkPoolTable.tsx
- apps/hubble-stats/components/NetworkTokenTable/NetworkTokenTable.tsx
- apps/hubble-stats/components/PoolOverviewItem/PoolOverviewItem.tsx
- apps/hubble-stats/containers/OverviewChartsContainer/OverviewChartsCmp.tsx
- apps/hubble-stats/containers/OverviewChartsContainer/OverviewChartsContainer.tsx
- apps/hubble-stats/containers/PoolChartsContainer/PoolChartsCmp.tsx
- apps/hubble-stats/containers/PoolChartsContainer/PoolChartsContainer.tsx
- apps/hubble-stats/containers/PoolChartsContainer/index.ts
- apps/hubble-stats/containers/PoolOverviewContainer/PoolOverviewContainer.tsx
- apps/hubble-stats/containers/PoolTransactionsTableContainer/PoolTransactionsTableCmp.tsx
- apps/hubble-stats/containers/index.ts
- apps/hubble-stats/data/getOverviewChartsData.ts
- apps/hubble-stats/data/getPoolChartsData.ts
- apps/hubble-stats/data/getPoolTransactionsData.ts
- apps/hubble-stats/data/index.ts
- libs/webb-ui-components/src/components/Breadcrumbs/BreadcrumbsItem.tsx
- libs/webb-ui-components/src/components/Breadcrumbs/types.ts
- libs/webb-ui-components/src/components/ChartContainer/ChartContainer.tsx
- Add Pool Charts component
- Add dummy data for charts
- Minor refactoring across small components
- Closes #1346 
https://github.com/webb-tools/webb-dapp/assets/69841784/26a821ab-21f5-4193-b42e-263059401344
-----
> chore: add dummy data for Overview Charts

- libs/abstract-api-provider/src/relayer/webb-relayer.ts
- libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
- libs/web3-api-provider/src/webb-provider.ts
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- package.json
- yarn.lock
- Fix the relayer status polling issue
- Bump viem & wagmi version
- Not set the gas limit on the deposit flow
- Closes https://github.com/webb-tools/webb-dapp/issues/1513
> Fix Relayer Status Polling Issue

- .github/workflows/deploy-bridge-dapp-dev.yml
- .github/workflows/deploy-faucet.yml
- .github/workflows/deploy-hubble-stats.yml
- .github/workflows/deploy-stats-dapp-dev.yml
- .github/workflows/deploy-tangle-website.yml
- .github/workflows/deploy-webbsite-dev.yml
- package.json
- yarn.lock
- Install netlify cli to project level
- Update workflows file to use local netlify
- Closes https://github.com/webb-tools/webb-dapp/issues/1541
> Fix Netlify Build

- .github/workflows/deploy-faucet.yml
- apps/faucet/src/config/tokens.ts
- libs/dapp-config/src/anchors/anchor-config.ts
- package.json
- yarn.lock
- Update to the latest Orbit Deployment
```
Bridge Address: 0x7C6C8Ed46a66Dac4132784c0a9C707e83bAccA05
Anchor Address: 0x7aA556dD0AF8bed063444E14A6A9af46C9266973
Webb Wrapped tTNT (webbtTNT): 0x58BA29259Aab901179A07899235e3CB88afE9079
WETH: 0x233410c6b87E2DB946D472423a1d3378F6DC91Df
MultiCall3: 0xDAfAD783A5dc54097e2FeB6684E7Ece615Cff3aA
```
- Closes 
-----
> Orbit Deployment 20230814 01

- apps/stats-dapp/src/utils/getProposalsData.ts
- package.json
- yarn.lock
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>## Summary of changes
- Use the correct package to decode proposals
> Use Correct Package to Decode Proposals

- .eslintignore
- .lycheeignore
- .prettierignore
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
> [RELEASE] DKG Stats dApp - September 2, 2021

- apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
- apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
- apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
- apps/bridge-dapp/src/hooks/useShieldedAssets.ts
- libs/dapp-config/src/chains/chain-config.interface.ts
- libs/dapp-config/src/chains/evm/index.tsx
- libs/note-manager/src/note-manager.ts
- libs/webb-ui-components/src/utils/index.ts
- libs/webb-ui-components/src/utils/numberToString.ts
- Fix the small amount issue
- Calculate the refund fee properly
- Closes https://github.com/webb-tools/webb-dapp/issues/1590
> Fix Small Amount Issue & Calculate Refund Fee Correctly

- .lycheeignore
- apps/bridge-dapp/CHANGELOG.md
- apps/bridge-dapp/package.json
- apps/hubble-stats/CHANGELOG.md
- apps/hubble-stats/package.json
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
- Release new Hubble Bridge UI
- Release Hubble Stats with Overview and Pool Detail pages
- Release DKG Stats with fixes and improvements
> [RELEASE] 2023 Sep 09 - New Hubble Bridge UI, Hubble Stats and DKG Stats

- apps/hubble-stats/app/layout.tsx
- apps/hubble-stats/app/providers.tsx
- apps/hubble-stats/components/charts/AreaChart.tsx
- apps/hubble-stats/components/charts/BarChart.tsx
- apps/hubble-stats/components/charts/VolumeChart.tsx
- apps/hubble-stats/components/sideBar/sideBarProps.tsx
- apps/hubble-stats/containers/Layout/Layout.tsx
- apps/hubble-stats/containers/OverviewChipsContainer/OverviewChipsContainer.tsx
- libs/webb-ui-components/src/components/SideBar/Footer.tsx
- libs/webb-ui-components/src/components/SideBar/SideBar.tsx
- libs/webb-ui-components/src/components/SideBar/SideBarMenu.tsx
- libs/webb-ui-components/src/components/SideBar/types.ts
- libs/webb-ui-components/src/components/ThemeToggle/ThemeToggle.tsx
- libs/webb-ui-components/src/components/ThemeToggle/types.ts
- libs/webb-ui-components/src/hooks/useDarkMode.ts
- package.json
- yarn.lock
- Fix the theme flickering on Hubble Stats
- Closes https://github.com/webb-tools/webb-dapp/issues/1598
https://github.com/webb-tools/webb-dapp/assets/60747384/0dbd1a2c-be48-42a6-9df7-03dc906ccefe
> Fix Hubble Stats Theme Flickering

- apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
- apps/hubble-stats/components/Breadcrumbs/types.ts
- apps/hubble-stats/components/PoolWrappingTable/PoolWrappingTable.tsx
- apps/hubble-stats/constants/subgraphs.ts
- apps/hubble-stats/constants/vanchor.ts
- apps/hubble-stats/data/getPoolOverviewTableData.ts
- apps/hubble-stats/data/getPoolTransactionsData.ts
- apps/hubble-stats/data/getPoolWrappingTableData.ts
- apps/hubble-stats/next.config.js
- apps/hubble-stats/utils/getVAnchorMapFromOnChainData.ts
- Fix duplicate tokens in composition
- Update currency for each row
- Update constant to handle data from local chains
- Closes #1626 
https://github.com/webb-tools/webb-dapp/assets/69841784/43aa0b94-dd6c-47a2-80e1-82e4b8b5044b
-----
> Hubble Stats: Fix Bugs in Pool Wrapping Table

- apps/bridge-dapp/src/pages/Hubble/Bridge/SelectPool.tsx
- apps/bridge-dapp/src/pages/Hubble/Bridge/SelectToken.tsx
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- Fix invalid `BigNumber` string on the transfer flow
- Remove dest chain on token and pool selection card
- Closes https://github.com/webb-tools/webb-dapp/issues/1645
> Fix Invalid BigNumber String on Tranfer flow

- .lycheeignore
- apps/bridge-dapp/CHANGELOG.md
- apps/bridge-dapp/package.json
- apps/faucet/CHANGELOG.md
- apps/faucet/package.json
- apps/hubble-stats/CHANGELOG.md
- apps/hubble-stats/package.json
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
- Release Hubble Bridge
- Release Hubble Stats
- Release DKG Stats
- Release Faucet
> [RELEASE] 2023 Sep 19 - Hubble Bridge, Hubble Stats, Faucet and DKG Stats

- apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
- Force reload when users navigate to any page
- Closes #1672 
https://github.com/webb-tools/webb-dapp/assets/69841784/ccb4688a-572d-496c-b53e-582dc562bf58
-----
> chore: fix pages not reload when users navigate back and forth

- apps/stats-dapp/src/utils/getProposalsData.ts
- Show chain name in proposal detail page.
- Closes #1656 
https://github.com/webb-tools/webb-dapp/assets/53374218/d2e87778-5e47-4a58-b2f9-c1ebebfcc19e
> Show chain name in proposal detail

- libs/dapp-types/src/Props.ts
- libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
- libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
- libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
Fixes some content in the dApp, removes unused artifacts.
> Content fixes, spelling fix

- apps/bridge-dapp/src/components/Header/Header.tsx
- libs/webb-ui-components/src/components/NavigationMenu/NavigationMenuContent.tsx
- libs/webb-ui-components/src/components/NavigationMenu/types.ts
- Updates bridge header dropdown menu items.
- Closes #1668
> Updates bridge header dropdown menu items

- apps/hubble-stats/app/layout.tsx
- libs/webb-ui-components/src/constants/index.ts
- package.json
- yarn.lock
- Add metadata for Hubble Stats
- Closes #1665 
-----
> Add metadata in layout in Hubble Stats

- libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
- Keeps the active chain at the top and sorts all remaining chains alphabetically.
- Closes #1449 
-----
> Sort all non-active chains alphabetically

- apps/faucet/src/components/ProcessingModal.tsx
- apps/faucet/src/components/RecipientAddressInput.tsx
- apps/faucet/src/containers/InputsContainer.tsx
- apps/faucet/src/containers/MintButtonContainer.tsx
- apps/faucet/src/pages/api/auth/signin/twitter.ts
- apps/faucet/src/provider/index.tsx
- apps/faucet/src/utils/isAllowSubstrateAddress.ts
- apps/faucet/src/utils/isTwitterRateLimitError.ts
- libs/dapp-types/src/utils/index.ts
- libs/dapp-types/src/utils/isSubstrateAddress.ts
- libs/dapp-types/src/utils/isValidAddress.ts
- libs/webb-ui-components/src/constants/index.ts
- libs/webb-ui-components/src/css/layer-components.css
- Adding Substrate support to the faucet.
- Closes https://github.com/webb-tools/webb-dapp/issues/1726
> Substrate Support on Faucet

- apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/index.tsx
- apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
- apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
- Disable the destination amount input field across all transaction flows including deposit, transfer, and withdrawal
- Closes #1699 
Uploading Screen Recording 2023-10-05 at 11.23.16.mov…
-----
> Disable amount input for destination accross flows

- apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
- Fixes incorrect threshold values in key detail page.
- Closes #1741 
https://github.com/webb-tools/webb-dapp/assets/53374218/4140aa3b-0c96-4387-9b72-29c828524d5d
> Fixes incorrect threshold values in key detail page

- apps/stats-dapp/src/public/index.html
Updated SEO description.
- Closes 
-----
> Updated SEO description

- .lycheeignore
- apps/bridge-dapp/CHANGELOG.md
- apps/bridge-dapp/package.json
- apps/bridge-dapp/src/hooks/useConnectButtonProps.ts
- apps/faucet/CHANGELOG.md
- apps/faucet/package.json
- apps/faucet/src/pages/_app.tsx
- apps/hubble-stats/CHANGELOG.md
- apps/hubble-stats/package.json
- apps/stats-dapp/CHANGELOG.md
- apps/stats-dapp/package.json
- libs/dapp-config/src/anchors/anchor-config.ts
- libs/note-manager/src/note-manager.ts
- Fix bridge small UI issues
- Release app
- Fix faucet footer width
> [RELEASE] 2023 Oct 05 - Hubble Bridge, Hubble Stats and DKG Stats

- apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
- libs/webb-ui-components/src/components/TransactionInputCard/TransactionInputCard.tsx
- Removal of Chain Selection Option in Withdrawal Flow on Destination Input
- Closes #1700
-----
> Removal of Chain Selection Option in Withdrawal Flow on Destination Input

- package.json
- yarn.lock
- Bump Netlify Next.js runtime
> Bump Netlify Next.js Runtime

- apps/faucet/src/utils/sidebar.ts
- apps/hubble-stats/components/HeaderChipItem/HeaderChipItem.tsx
- apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedTablesContainer.tsx
- libs/webb-ui-components/src/components/SideBar/SideBar.tsx
- libs/webb-ui-components/src/next-utils/sideBarState.ts
- libs/webb-ui-components/src/utils/getCookieItem.ts
- libs/webb-ui-components/src/utils/index.ts
-
- Closes #1796 
https://github.com/webb-tools/webb-dapp/assets/69841784/5eaa93ec-baa9-47c2-b5df-627578081556
---
> Minor bugs on Faucet and Hubble Stats (Shielded Pool Table + Header Chip + Sidebar)

- apps/bridge-dapp/src/components/Header/ChainButton.tsx
- apps/bridge-dapp/src/components/Header/Header.tsx
- apps/bridge-dapp/src/components/Header/WalletDropdown/index.tsx
- libs/webb-ui-components/src/components/ListCard/ListItem.tsx
- libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
- Implement Mobile and Tablet Variant for Connect Wallet Modal
- Update Bridge Header to match design for mobile and desktop
- Closes #1801 
https://github.com/webb-tools/webb-dapp/assets/69841784/3b0de38e-aa3c-4081-8d8c-20548f792ab2
---
> Implement Mobile Variant for Connect Wallet Modal

- .github/workflows/check-build.yml
- .github/workflows/check-lint.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-bridge-dapp-dev.yml
- .github/workflows/deploy-faucet.yml
- .github/workflows/deploy-stats-dapp-dev.yml
- .github/workflows/deploy-storybook-docs.yml
- .github/workflows/ui-review.yml
- Adding `feature` branch to github CI
> Adding `feature` Branch to Github CI

- .github/workflows/check-lint.yml
- README.md
- apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
- apps/tangle-dapp/constants/polkadot.ts
- apps/tangle-dapp/data/ValidatorTables/getActiveValidators.ts
- apps/tangle-dapp/data/ValidatorTables/getWaitingValidators.ts
- apps/tangle-dapp/types/index.ts
- Remove minimum stake column from validator tables.
> EVM Staking - Remove minimum stake column from validator tables

- .github/CONTRIBUTING.md
- .husky/commit-msg
- .husky/pre-push
- README.md
- commitlint.config.js
- package.json
- yarn.lock
- The `husky` and `commitlint` packages were accidentally deleted in a previously merged commit, this addresses that.
- I've added most rules as warnings and no unusual rules, to ensure smooth integration.
- Added appropriate section regarding commit message guidelines to `CONTRIBUTING.md` file for new contributors.
Here are some example proposed commit message formats:
- `chore(zk-explorer): Fixed husky and commitlint integration`
- `docs: Added documentation for commit message guidelines`
- `feat(bridge-dapp): Fixed a certain bug (#123)`
The part after the commit type is the **scope**, where it allows you to define what area of the monorepo was affected. These are the different available scopes:
- `bridge-dapp`
- `faucet`
- …
> chore: Re-integrate `husky` and `commitlint` which were accidentally deleted

- apps/tangle-dapp/app/providers.tsx
- libs/webb-ui-components/src/provider/index.tsx
- libs/webb-ui-components/src/provider/types.ts
- Fix Flicker Theme issue on Tangle Dapp
- Closes #2007 
https://github.com/webb-tools/webb-dapp/assets/69841784/48696f65-b07b-47be-b45c-c75226510885
---
> Fix Flicker Theme issue on Tangle Dapp

- .lycheeignore
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/data/DelegationsPayouts/usePayouts.ts
- apps/tangle-dapp/package.json
> [RELEASE] 2024 Feb 07 - Tangle Dapp

- apps/tangle-dapp/app/nomination/[validatorAddress]/ValidatorOverviewCard.tsx
- apps/tangle-dapp/app/services/[id]/page.tsx
- apps/tangle-dapp/app/services/[serviceId]/DetailTabs.tsx
- apps/tangle-dapp/app/services/[serviceId]/ParticipantsTable.tsx
- apps/tangle-dapp/app/services/[serviceId]/page.tsx
- apps/tangle-dapp/components/Breadcrumbs/Breadcrumbs.tsx
- apps/tangle-dapp/components/ServiceTable/ServiceTable.tsx
- apps/tangle-dapp/components/SocialChip.tsx
- apps/tangle-dapp/components/index.ts
- apps/tangle-dapp/components/skeleton/ContainerSkeleton.tsx
- apps/tangle-dapp/components/skeleton/SkeletonRow.tsx
- apps/tangle-dapp/components/skeleton/index.ts
- apps/tangle-dapp/data/ServiceDetails/index.ts
- apps/tangle-dapp/data/ServiceDetails/useServiceParticipants.ts
- apps/tangle-dapp/types/index.ts
- libs/icons/src/CodeFill.tsx
- libs/icons/src/index.ts
- Add service details page
- Handle Breadcrumbs
- Participants Table
- Closes #1981 
https://github.com/webb-tools/webb-dapp/assets/69841784/8ccd6d09-384f-47b6-af2b-f0ae8415610e
https://github.com/webb-tools/webb-dapp/assets/69841784/2ee34b2f-ceb6-45c7-b535-3b4773de7307
---
> Participants Table on Service Details page

- .github/workflows/release.yml
- Include the previously missed `tangle-dapp` in the GA release workflow.
> fix(tangle-dapp): Adding tangle-dapp to release GA workflow

- apps/tangle-dapp/app/account/Actions.tsx
- apps/tangle-dapp/app/claim/page.tsx
- apps/tangle-dapp/constants/faq.tsx
- apps/testnet-leaderboard/components/FAQSection/index.tsx
- Updates descriptions of leaderboard, token allocations, and adds links to new allocation document pages on docs.tangle.
---
> Updates to language on FAQ and descriptions on Airdrop claims portal

- .lycheeignore
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Bumped `tangle-dapp`'s version.
- Updated `CHANGELOG`.
> [RELEASE] 2024 March 12 - Tangle Dapp

- apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
> style(tangle-dapp): Update `RecentTxContainer` component

- apps/tangle-dapp/containers/Layout/Layout.tsx
- libs/webb-ui-components/src/components/Footer/Footer.tsx
- libs/webb-ui-components/src/components/Footer/types.ts
- libs/webb-ui-components/src/components/Socials/Socials.tsx
- libs/webb-ui-components/src/components/Socials/types.ts
- libs/webb-ui-components/src/constants/index.ts
- libs/webb-ui-components/src/types/index.ts
> docs(tangle-dapp): Update footer links

- .lycheeignore
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Bumped `tangle-dapp`'s version.
- Updated `CHANGELOG`.
- Had to resolve merge conflicts from `master -> dev`, since for some reason there's a commit in `master` ahead of `dev`.
> [RELEASE] 2024 March 21 - Tangle Dapp

- apps/bridge-dapp/src/containers/WalletModalContainer/WalletModalContainer.tsx
- apps/tangle-dapp/containers/WalletModalContainer/WalletModalContainer.tsx
- apps/tangle-dapp/utils/polkadot/utils.ts
- libs/api-provider-environment/src/WebbProvider/index.tsx
- libs/dapp-config/src/wallets/wallets-config.tsx
- libs/dapp-types/src/WebbError.ts
- libs/dapp-types/src/errors/WalletNotInstalledError.ts
- libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
- libs/webb-ui-components/src/components/WalletConnectionCard/types.ts
- libs/webb-ui-components/src/components/WalletModal/WalletModal.tsx
- libs/webb-ui-components/src/components/WalletModal/types.ts
- Update content for Wallet Modal
- Update variable name from Polkadot to Polkadotjs
- Closes #2093 
https://github.com/webb-tools/webb-dapp/assets/69841784/d5def211-c3b6-40cc-85ca-91ae6a31eab5
---
> Update wallet modal content

- apps/tangle-dapp/app/claim/EligibleSection.tsx
- apps/tangle-dapp/app/claim/page.tsx
- apps/tangle-dapp/app/claim/success/SuccessClient.tsx
- apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails.tsx
- apps/tangle-dapp/data/balances/useBalances.ts
- Update copy to use TNT for claims
- Update balance calculation on account page (incorrect `transferrable` balance leads to negative balance).
> feat: use TNT token name

- libs/webb-ui-components/src/constants/index.ts
> Update Whitepaper link

- .lycheeignore
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Bumped `tangle-dapp`'s version.
- Updated `CHANGELOG`.
> [RELEASE] 2024 March 29 - Tangle Dapp

- apps/bridge-dapp/src/containers/Layout/Layout.tsx
- apps/tangle-dapp/app/nomination/page.tsx
- apps/tangle-dapp/containers/Layout/FeedbackBanner.tsx
- apps/tangle-dapp/containers/Layout/Layout.tsx
- libs/icons/src/BoxLine.tsx
- libs/icons/src/index.ts
- libs/webb-ui-components/src/components/Banner/Banner.tsx
- libs/webb-ui-components/src/components/Banner/types.ts
- Update Banner components in `webb-ui-components`
- Add Feedback Banner to Tangle Dapp
- Closes #2103 
https://github.com/webb-tools/webb-dapp/assets/69841784/7ffccd55-a8ae-471a-88e4-6fd7edf7a88d
---
> Add Feedback Banner to Tangle Dapp

- apps/tangle-dapp/app/claim/EligibleSection.tsx
> Copy fix for claims

- apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
- Proposing to update copy to introduce Tangle dApp on Account Dashboard, as recent tx is no longer going to be implemented. 
- Closes
---
> Update copy to remove recent tx details

- apps/tangle-dapp/app/claim/EligibleSection.tsx
- apps/tangle-dapp/app/claim/page.tsx
- apps/tangle-dapp/app/claim/types.ts
- libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
- Showing Free & Vesting Balance in Claim page
- Fix Flicker problem after successfully claimed
- Remove hover state on Checkbox component, it is unecessary and causes bad UI
- Closes #2170 
https://github.com/webb-tools/webb-dapp/assets/69841784/66364b00-8fc1-4969-b6aa-db294c2cdddc
---
>  Pre-launch audit: Show vesting info on Claim Airdrop page + Fix Flicker problem when successfully claimed

- apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
- Update payouts table status to let the users know that payouts work is under development.
> chore(tangle-dapp): Update payouts table status

- apps/tangle-dapp/components/NominatorStatsItem/dataHooks.ts
- apps/tangle-dapp/containers/BondMoreTxContainer/BondMoreTxContainer.tsx
- apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
- apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
- apps/tangle-dapp/data/NominatorStats/useTokenWalletFreeBalance.ts
- apps/tangle-dapp/utils/polkadot/utils.ts
- Test `View Explorer` link on Account page across all the networks
- Fix Free Balance display on Nomination page for EVM
- Closes #2155 (tested - everything works fine)
https://github.com/webb-tools/webb-dapp/assets/69841784/b6d8df1c-da76-4eda-b150-8d0705193b8a
---
> Test `View Explorer` link on Account page +  Fix Free Balance display on Nomination page for EVM wallet

- .lycheeignore
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Updated CHANGELOG
- Bumped package version
> [RELEASE] 2024 April 10 - Tangle Dapp

- apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
- Add View Account button on nomination page
---
> Add View Account button on nomination page

- apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
- Add View Account button on nomination page
- Closes
---
> Add View Account button on nomination page (#2211)

- apps/tangle-dapp/components/TableStatus/TableStatus.tsx
- apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
- apps/tangle-dapp/data/ValidatorTables/useValidatorIdentityNames.ts
- apps/tangle-dapp/data/ValidatorTables/useValidators.ts
- apps/tangle-dapp/hooks/usePolkadotApiRx.ts
- apps/tangle-dapp/utils/polkadot/nominators.ts
- Mainnet network is having issues displaying the validator table, this has been fixed as it was the bug due to usage of `any` because of previously outdated Substrate types.
- Updated copy and button label for the Payouts container, which shows that the payouts feature is under development. Made it more clear and adde a max width.
- Closes #2219
https://github.com/webb-tools/webb-dapp/assets/101931215/8e0b8a09-b67e-40e6-b98e-24790fd5eabf
---
> fix(tangle-dapp): Fix validator table in Nomination page, on mainnet network

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Updated `CHANGELOG`.
- Bumped package version
> [RELEASE] 2024 April 12 - Tangle Dapp

- libs/webb-ui-components/src/components/Input/Input.tsx
- Handle cursor position when changing input value
- Tested on all inputs in Account and Nomination page
- Closes #2200 
https://github.com/webb-tools/webb-dapp/assets/69841784/ce96c361-9b76-4b63-8d59-d3d1cff826b1
---
> Fix cursor moves to the end when changing value in input

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Updated CHANGELOG.md file.
- Bumped Tangle dApp version
> [RELEASE] 2024 April 29 - Tangle dApp

- apps/tangle-dapp/app/nomination/[validatorAddress]/page.tsx
- apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
- apps/tangle-dapp/components/tableCells/HeaderCell.tsx
- apps/tangle-dapp/constants/env.ts
- apps/tangle-dapp/containers/Layout/Layout.tsx
- apps/tangle-dapp/data/NominationsPayouts/useNominations.ts
- apps/tangle-dapp/data/ValidatorTables/useValidators.ts
- apps/tangle-dapp/types/index.ts
- Add # of Active Services and Restake Amount to Validators Table in Nomination
- Hide Restaking related features on production
- Closes #1992 
https://github.com/webb-tools/webb-dapp/assets/69841784/0d7ce1ab-0d6f-46da-ac12-b39bc8ee3424
---
> feat(tangle-dapp): Add # of Active Services and Restake Amount to Validators Table in Nomination

- apps/tangle-dapp/components/ValidatorList/ValidatorList.tsx
- apps/tangle-dapp/components/ValidatorList/types.ts
- apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
- apps/tangle-dapp/containers/UpdateNominationsTxContainer/SelectValidators.tsx
- apps/tangle-dapp/containers/UpdateNominationsTxContainer/UpdateNominationsTxContainer.tsx
- apps/tangle-dapp/containers/UpdateNominationsTxContainer/types.ts
- libs/webb-ui-components/src/components/Table/TData.tsx
- libs/webb-ui-components/src/components/Table/THeader.tsx
- libs/webb-ui-components/src/components/Table/Table.tsx
- libs/webb-ui-components/src/components/Table/types.ts
- Refactored the validator list table to maximize the utilization of the [react-table](https://tanstack.com/table/v8/docs/introduction) functionality. This includes global searching, row selection, and sorting, eliminating the need for re-implementing these functions.
- Moved the row selection state inside the table component to prevent unnecessary re-renders.
- Optimized search performance by changing the selected validator list from an `Array` to a `Set`.
- Implemented `useEffect` (with `startTransition`) to ensure synchronization of selected validators with the parent component without UI blocking.
- Employed memoization for both the table header and table data components.
_Specify any issues …
> fix(tangle-dapp): Slow Rendering of Checkboxes When Clicked

- apps/bridge-dapp/src/pages/Hubble/Bridge/SelectChain.tsx
- libs/dapp-config/src/chains/evm/index.tsx
- libs/dapp-types/src/EVMChainId.ts
- Updated local chain IDs and ports to match with Orbit repo.
- Added filtering for `undefined` destination chains.
> fix(bridge-dapp): Updated Local Chain Ids & Rpc Ports

- apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
- apps/tangle-dapp/containers/BalancesTableContainer/useLongestVestingScheduleTime.ts
- apps/tangle-dapp/data/vesting/useVestingInfo.ts
> feat(tangle-dapp): Show longest vesting schedule info

- apps/tangle-dapp/app/bridge/AmountAndTokenInput.tsx
- apps/tangle-dapp/app/bridge/ChainSelectors.tsx
- apps/tangle-dapp/app/bridge/hooks/useBridgeType.ts
- apps/tangle-dapp/constants/bridge.ts
- apps/tangle-dapp/context/BridgeContext.tsx
- apps/tangle-dapp/types/bridge.ts
- apps/tangle-dapp/types/index.ts
- libs/webb-ui-components/src/components/buttons/ChainOrTokenButton.tsx
- Hardcode chain options (dummy data):  Source -> Destination + List Tokens Available (similar approach as Subbridge)
- Prepare 4 scenarios of tx
- Minor UI updates
- Closes #2325 
https://github.com/webb-tools/webb-dapp/assets/69841784/d4fb5fb7-64c9-4c18-a3b6-4fbc5d099295
---
> feat(tangle-dapp): Setup the code logic to handle different scenarios of bridging

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Updated CHANGELOG.md file.
- Bumped Tangle dApp version.
> [RELEASE] 2024 May 27 - Tangle dApp

- apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
- apps/tangle-dapp/data/payouts/usePayoutsAvailability.ts
- Some checks were missing which was causing payouts to crash.
- Closes
---
> fix(tangle-dapp): Fix payouts bug

- apps/tangle-dapp/.eslintrc.json
- apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
- apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
- libs/webb-ui-components/src/constants/index.ts
- Fixed link to docs.
- Updated site description text shown on account page.
- Removed `simple-import-sort` eslint plugin, since it is causing annoyances and doesn't really provide any benefit.
- Closes #2343
---
> fix(tangle-dapp): Fix links and site description copy

- apps/bridge-dapp/src/utils/getEstimatedGasFeesByChain.ts
- apps/tangle-dapp/app/layout.tsx
- apps/tangle-dapp/app/providers.tsx
- apps/tangle-dapp/components/UpdateMetadataButton.tsx
- apps/tangle-dapp/next.config.js
- apps/tangle-dapp/project.json
- libs/api-provider-environment/src/WebbProvider/index.tsx
- libs/dapp-config/src/chains/evm/index.tsx
- libs/dapp-config/src/wagmi-config.ts
- libs/web3-api-provider/src/ext-provider/web3-accounts.ts
- libs/web3-api-provider/src/webb-provider.ts
- libs/web3-api-provider/src/webb-provider/chain-query.ts
- libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
- libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
- libs/webb-ui-components/src/hooks/useBreakpoint.ts
- libs/webb-ui-components/src/hooks/useIsomorphicEffect.ts
- libs/webb-ui-components/src/hooks/useMediaQuery.ts
- libs/webb-ui-components/src/utils/isBrowser.ts
- libs/webb-ui-components/src/utils/isSSR.ts
- package.json
- yarn.lock
- Added UI hooks to enhance the responsiveness.
- Applied conditional rendering on WalletConnectionCard to fix the Icon Not Showing error.
- Configured Wagmi to support both SSR and non-SSR dApps.
- Fixed only showing the update metadata button for Substrate wallets.
- Added bundle analyzer to tangle-dapp.
- Closes https://github.com/webb-tools/webb-dapp/issues/2358
- Closes https://github.com/webb-tools/webb-dapp/issues/2361
---
https://github.com/webb-tools/webb-dapp/assets/60747384/f6e290fa-b14d-4963-ab63-943e01a3f413
> fix(tangle-dapp): Tangle dApp Iteration Jun 05, 2024

- apps/tangle-dapp/app/bridge/AmountAndTokenInput.tsx
- apps/tangle-dapp/app/bridge/BridgeConfirmationModal.tsx
- apps/tangle-dapp/app/bridge/BridgeContainer.tsx
- apps/tangle-dapp/app/bridge/ChainSelectors.tsx
- apps/tangle-dapp/app/bridge/FeeDetails.tsx
- apps/tangle-dapp/app/bridge/hooks/useActionButton.ts
- apps/tangle-dapp/utils/convertBnToDecimal.ts
- Show Bridge Transaction Confirmation Modal if the user is ready to make a tx
- Make Chain Selector bigger
- Closes #2376 
https://github.com/webb-tools/webb-dapp/assets/69841784/27cc0050-ad6f-43f5-9147-960a3a36f320
---
> feat(tangle-dapp): Show Bridge Transaction Confirmation Modal

- apps/tangle-dapp/app/robots.txt
- Add `robots.txt` to optimzie SEO
- Related https://github.com/webb-tools/webb-dapp/issues/2405
> feat(tangle-dapp): Add `robots.txt` to optimzie SEO

- .github/actions/create-release/gh-release-script.js
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Adjust the release script to align with the updated changelog format.
- Release tangle-dapp version `v.0.0.10`.
> [RELEASE] tangle-dapp v0.0.10

- apps/tangle-dapp/app/api/hello/route.ts
- apps/tangle-dapp/app/claim/layout.tsx
- apps/tangle-dapp/app/claim/page.tsx
- apps/tangle-dapp/app/layout.tsx
- apps/tangle-dapp/app/nomination/[validatorAddress]/page.tsx
- apps/tangle-dapp/app/nomination/layout.tsx
- apps/tangle-dapp/app/nomination/page.tsx
- apps/tangle-dapp/app/page.tsx
- Removed the Suspense components.
- Force static renders to prevent timed out issue on SSR functions.
> fix(tangle-dapp): Fix Timed Out Error

- apps/tangle-dapp/components/ValidatorSelectionTable/ValidatorSelectionTable.tsx
- apps/tangle-dapp/components/ValidatorSelectionTable/types.ts
- apps/tangle-dapp/components/tableCells/TokenAmountCell.tsx
- Fix sort/scroll issues on nomination selection list modal
- Fix overflow on nomination list modal
- Closes #2378 
https://github.com/webb-tools/webb-dapp/assets/69841784/b715317b-0bc8-4ee0-b4ba-ffe48edf7897
---
> fix(tangle-dapp): Fix sort/scroll issues on nomination selection list modal

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- Release tangle-dapp `v0.0.11`
> [RELEASE] tangle-dapp v0.0.11

- .github/CODE_OF_CONDUCT.md
- apps/bridge-dapp/src/pages/Account/index.tsx
- apps/tangle-dapp/components/AmountInput/AmountInput.tsx
- apps/tangle-dapp/components/ValidatorSelectionTable/ValidatorSelectionTable.tsx
- apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
- apps/tangle-dapp/components/ValidatorTable/types.ts
- apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
- apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
- apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
- apps/tangle-dapp/hooks/useInputAmount.ts
- libs/webb-ui-components/src/components/TableAndChartTabs/TableAndChartTabs.tsx
- libs/webb-ui-components/src/components/TableAndChartTabs/types.ts
- Add Search functionalities for Validator tables
- Mix clicking `Max` button on `AmountInput` not working
- Closes #2438 
- Closes #2437 
https://github.com/user-attachments/assets/75551a1c-ecf2-46ff-a72c-0bb4eec7bbd0
https://github.com/user-attachments/assets/ab045f0c-ef12-4d8c-ab82-95d6b5812762
---
> feat(tangle-dapp): Add Search functionalities for Validator tables + Fix Nomination Modal

- apps/bridge-dapp/project.json
- apps/zk-explorer/project.json
- Disabled unused targets to optimize build time. 
> perf(repo): Disabled Unused Targets

- apps/tangle-dapp/containers/PayoutAllTxContainer/PayoutAllTxContainer.tsx
- apps/tangle-dapp/next.config.js
- Fix payout modal overflowing
- Closes https://github.com/webb-tools/webb-dapp/issues/2386
> fix(tangle-dapp): Fix payout modal overflowing

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- yarn.lock
- Release tangle-dapp `v0.0.12`.
> [RELEASE] tangle-dapp v0.0.12

- libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
- libs/webb-ui-components/src/components/ListCard/ListItem.tsx
- libs/webb-ui-components/src/components/ListCard/types.ts
- libs/webb-ui-components/src/stories/templates/ChainListCard.stories.tsx
- Update UI for hover and disable state for `ChainListCard`
- Update Storybook for `ChainListCard`
- Closes #2458 
https://github.com/user-attachments/assets/4e523989-baba-405f-b9f3-3acdbbc4381a
---
> chore(tangle-dapp): Update Chain selection menu dropdown

- apps/tangle-dapp/components/ValidatorSelectionTable/ValidatorSelectionTable.tsx
- libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
- libs/webb-ui-components/src/css/radix-ui.css
- Update Checkbox component in `webb-ui-components` lib
- Closes #2457 
https://github.com/user-attachments/assets/3e0203bb-87f4-470d-928f-ca0787c3c6dd
---
> feat(tangle-dapp): Update Checkbox component

- apps/tangle-dapp/lib/hyperlane/assembleChainMetadata.ts
- Fixes bridge disabled button
- Closes #2591
> fix(tangle-dapp): Fix bridge disabled button

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/components/Sidebar/sidebarProps.ts
- apps/tangle-dapp/package.json
- Release Tangle dApp `v0.0.15`
- Closes
---
> [RELEASE] tangle-dapp v0.0.15

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- libs/tangle-shared-ui/src/components/UpdateMetadataButton/UpdateMetadataButton.tsx
- Add active wallet check to ensure only checking metadata update for Substrate wallet
- Release Tangle dApp v0.0.17
> [RELEASE] Release tangle-dapp v0.0.17

- apps/tangle-dapp/src/containers/LockedBalanceDetailsModal.tsx
- apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
- apps/tangle-dapp/src/pages/restake/unstake/index.tsx
- apps/tangle-dapp/src/pages/restake/withdraw/index.tsx
- libs/tangle-shared-ui/src/components/ListModal.tsx
- [Update modal props after merge conflicts messed up](https://github.com/tangle-network/dapp/commit/94343f551420c596fe74f64fe0d76eb33ccb3082)
- Closes `NaN`
> fix(tangle-dapp): Update modal props after merge conflicts

- apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
- libs/dapp-config/src/chains/substrate/index.tsx
- libs/tangle-shared-ui/src/components/tables/Operators/VaultsDropdown.tsx
- libs/tangle-shared-ui/src/components/tables/Operators/index.tsx
- libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
- libs/tangle-shared-ui/src/data/restake/utils/randOperator.ts
- libs/tangle-shared-ui/src/types/index.ts
- libs/tangle-shared-ui/src/utils/restake/delegationsToVaultTokens.ts
- Utilize Decimal.js for floating-point numbers.
- Aggregate delegated amounts by ID.
- Display self-bonded amounts in the operator table.
- Closes https://github.com/tangle-network/dapp/issues/2777
- Closes https://github.com/tangle-network/dapp/issues/2776
https://github.com/user-attachments/assets/bcc15406-b5d1-4527-8ce6-ddb940f010d1
> feat(tangle-dapp): Aggregate Vault Token and Display Self-Bonded

- apps/tangle-dapp/src/components/account/RewardsAndPoints.tsx
- tsconfig.base.json
- Fix incorrect token symbol on unclaimed reward. 
- Closes `NaN`
> fix(tangle-dapp): Fix Incorrect Token Symbol on Unclaimed Reward

- apps/tangle-cloud/project.json
- apps/tangle-cloud/tsconfig.app.json
- apps/tangle-dapp/project.json
- apps/tangle-dapp/tsconfig.app.json
- package.json
- yarn.lock
- Fix the augmented type error by adding the resolution for `@polkadot/api`.
- Add type-checking for Tangle dApp and Tangle Cloud.
- Closes `NaN`
> feat(repo): Add Typecheck for dApps

- .lycheeignore
- apps/tangle-cloud/src/components/Sidebar.tsx
- libs/ui-components/src/components/Dropdown/DropdownButton.tsx
- libs/ui-components/src/components/Dropdown/types.ts
- Renamed props and added a custom arrow element prop to enhance the sidebar UI in Tangle Cloud.
- Closes
> refactor(ui-component/dropdown-button): change props name & add custom arrow prop

- .lycheeignore
- apps/tangle-cloud/src/app/app.tsx
- apps/tangle-cloud/src/components/Sidebar.tsx
- apps/tangle-cloud/src/pages/instances/layout.tsx
- apps/tangle-cloud/src/pages/instances/page.tsx
- apps/tangle-cloud/src/types/index.ts
- Update the router path using enum
- Init Instance page
- Closes
> fix(tangle-cloud): update router path

- libs/ui-components/src/hooks/useDarkMode.ts
- Fixes #2860 
- Closes #2860 
https://github.com/user-attachments/assets/9da8424d-9010-4fd3-8b56-f87091cbb823
> fix(ui-components): useDarkMode Resets on Page Refresh

- apps/tangle-dapp/src/components/Lists/AssetList.tsx
- Fixes #2871 
- Closes #2871 
https://github.com/user-attachments/assets/d5e2999b-e0da-427e-945c-eedfb483082a
> chore(tangle-dapp): Update Asset List Modal in Bridge

- apps/tangle-dapp/src/components/account/PromotionalBanner.tsx
- apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
- libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletButton.tsx
- libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletModal.tsx
- libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/NetworkSelectorDropdown.tsx
- libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx
- Update the promotional banner component's font size, color and increase slider size.
- Update the `Connect Wallet` modal's default copy.
- Change the connection status color to yellow if selected but not connected.
- Update the copy from `Wrong EVM chain connected` to `Switch to the selected network`.
- Set the Tangle chain as the default source chain on the Bridge.
- Closes #2869 
https://github.com/user-attachments/assets/14c3e735-a3f5-4f0d-880c-b686b643fa3b
https://github.com/user-attachments/assets/41b5ff65-edd7-4159-b5e6-34cd88c5b33d
> fix(tangle-dapp): Network switching & other fixes

- apps/tangle-cloud/src/components/TangleCloudCard.tsx
- apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
- apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
- apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
- apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
- apps/tangle-cloud/src/pages/instances/Instances/StoppedInstanceTable.tsx
- apps/tangle-cloud/src/pages/instances/Instances/index.tsx
- apps/tangle-cloud/src/pages/instances/Instances/type.ts
- apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
- apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/index.tsx
- apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/type.ts
- apps/tangle-cloud/src/pages/instances/TotalValueLocked/TotalValueLockedTable.tsx
- apps/tangle-cloud/src/pages/instances/TotalValueLocked/index.tsx
- apps/tangle-cloud/src/pages/instances/page.tsx
- apps/tangle-dapp/src/pages/restake/operators/[address]/index.tsx
- libs/tangle-shared-ui/src/data/blueprints/useFakeMonitoringBlueprints.ts
- libs/tangle-shared-ui/src/data/blueprints/useOperatorBlueprints.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveBlueprint.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
- libs/ui-components/src/constants/index.ts
- Implement mock logic for Tangle Cloud / Operator Home Page / Instance section
- In progress https://github.com/tangle-network/dapp/issues/2559
https://github.com/user-attachments/assets/00171e94-a8c7-4c35-8c83-2dff52c9d323
> feat(tangle-cloud): implement mock logic for Tangle Cloud Operator Home Page Instance section

- apps/tangle-cloud/src/components/NestedOperatorCell.tsx
- apps/tangle-cloud/src/components/accountStatsCard/AccountStatsCardHeader.tsx
- apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
- apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
- apps/tangle-cloud/src/pages/instances/Instances/type.ts
- apps/tangle-cloud/src/pages/instances/InstructionCard.tsx
- apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
- apps/tangle-cloud/src/pages/instances/page.tsx
- libs/tangle-shared-ui/src/data/blueprints/useFakeMonitoringBlueprints.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
- libs/ui-components/src/components/Dropdown/DropdownButton.tsx
- libs/ui-components/src/components/Dropdown/types.ts
- Implement home page UI for Deployer
- In progress: https://github.com/tangle-network/dapp/issues/2559
https://github.com/user-attachments/assets/8e5fc111-e214-4898-966c-cb81c3dcea33
> feat(tangle-cloud): building UI deployer home page

- apps/tangle-dapp/src/components/LiquidStaking/LstListItem.tsx
- apps/tangle-dapp/src/components/LiquidStaking/stakeAndUnstake/SelectedPoolIndicator.tsx
- apps/tangle-dapp/src/constants/liquidStaking/types.ts
- apps/tangle-dapp/src/containers/LsPoolsTable/LsPoolsTable.tsx
- apps/tangle-dapp/src/data/liquidStaking/useLsActivePoolDisplayName.ts
- apps/tangle-dapp/src/data/liquidStaking/useLsPools.ts
- apps/tangle-dapp/src/data/restake/useRestakeAsset.ts
- libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
- libs/tangle-shared-ui/src/types/restake.ts
- Handle empty asset names on the operator table.
- Handle empty pool names on the liquid staking page.
- Closes https://github.com/tangle-network/dapp/issues/2877
> chore: Handle Empty Names for Assets and Pools

- libs/tangle-shared-ui/src/data/restake/useRestakeAssetBalances.ts
- libs/tangle-shared-ui/src/types/error.ts
- Handle the case where there is no active account by returning an error in the `useRestakeAssetBalances.ts` hook, ensuring the loading state is set to false.
> fix(tangle-shared-ui): Fix Infinite Loading on Vault Table

- apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
- libs/icons/src/WalletIcon.tsx
- libs/icons/src/index.ts
- Always use the sender address as the default destination address.
- Allow users to enter different destination address.
- Closes #2870 
https://github.com/user-attachments/assets/0a66b581-0174-48b9-a81f-6ecb91ebe068
> chore(tangle-dapp): Update Bridge Destination Address Input

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- nx.json
- 🐛 Fix: Include all commitlint commit types in changelog generation https://github.com/tangle-network/dapp/commit/0b6ed05508a26b8f024319fe8f0f58f885ec1678.
- 🏇 Release: Tangle dApp v0.1.1.
- Closes `NaN`
> [RELEASE] Release Tangle dApp v0.1.1

- apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
- apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
- apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
- apps/tangle-dapp/src/containers/restaking/RestakeOverviewTabs.tsx
- apps/tangle-dapp/src/pages/restake/operators/[address]/OperatorInfoCard.tsx
- libs/tangle-shared-ui/src/data/blueprints/useBlueprintListing.ts
- libs/tangle-shared-ui/src/data/blueprints/useMonitoringBlueprints.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/blueprintHelpers.ts
- libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
- libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
- libs/tangle-shared-ui/src/data/restake/useOperatorConcentration.ts
- libs/tangle-shared-ui/src/data/restake/useOperatorTVL.ts
- libs/tangle-shared-ui/src/data/restake/useRestakeTVL.ts
- update the TVL calculation in use blueprint hook
- Completed: https://github.com/tangle-network/dapp/issues/2559
> fix(libs/tangle-shared-ui): update the TVL calculation in use blueprint hook

- apps/leaderboard/CHANGELOG.md
- apps/leaderboard/package.json
> [RELEASE] leaderboard v0.0.1

- apps/tangle-dapp/src/components/account/AccountSummaryCard.tsx
- apps/tangle-dapp/src/components/account/Actions.tsx
- apps/tangle-dapp/src/components/account/Balance.tsx
- libs/ui-components/src/components/Dropdown/AccountDropdownBody.tsx
- Update account card and actions.
- Make the switching account dropdown scrollable.
- Closes https://github.com/tangle-network/dapp/issues/2933
https://github.com/user-attachments/assets/d8669911-814b-4cc6-a1ff-469905fe34ca
> chore(tangle-dapp): Update Account Card Components

- apps/tangle-dapp/src/components/Lists/ChainList.tsx
- apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
- libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx
- libs/tangle-shared-ui/src/hooks/useLocalStorage.ts
- group chains by tag (live, test) in chain list component.
https://github.com/user-attachments/assets/49c5588a-044a-4e0e-8296-28357bac28c2
> chore(tangle-dapp): Group chains by chain type in ChainList component

- apps/leaderboard/src/app/Navbar.tsx
- apps/tangle-cloud/src/pages/instances/TotalValueLocked/index.tsx
- apps/tangle-dapp/src/components/PayoutsTable.tsx
- apps/tangle-dapp/src/components/ValidatorSelectionTable.tsx
- apps/tangle-dapp/src/components/ValidatorTable.tsx
- apps/tangle-dapp/src/components/nomination/NominationsTable.tsx
- apps/tangle-dapp/src/components/tableCells/HeaderCell.tsx
- apps/tangle-dapp/src/components/tableCells/index.ts
- apps/tangle-dapp/src/components/tableCells/types.ts
- apps/tangle-dapp/src/components/tables/Vaults/index.tsx
- apps/tangle-dapp/src/hooks/useVaultTableData.tsx
- apps/tangle-dapp/src/pages/nomination/[validatorAddress]/NodeSpecificationsTable.tsx
- libs/tangle-shared-ui/src/components/tables/HeaderCell.tsx
- libs/tangle-shared-ui/src/components/tables/VaultAssets/index.tsx
- libs/tangle-shared-ui/src/components/tables/VaultAssets/types.ts
- libs/tangle-shared-ui/src/data/rewards/useVaultRewards.ts
- libs/tangle-shared-ui/src/utils/createVaultMap.ts
- libs/ui-components/src/css/layer-components.css
- tailwind.config.ts
- Increase font size of vault table header.
- Remove the available column of the vault table.
- Improve the detail view of the vault table.
- Closes `NaN`
https://github.com/user-attachments/assets/86297aec-031a-4ba5-9a5f-e081d13cfa29
> chore(tangle-dapp): Improve Vault Table

- apps/tangle-dapp/src/components/Sidebar/sidebarProps.tsx
- apps/tangle-dapp/src/components/account/ActionItem.tsx
- apps/tangle-dapp/src/components/account/Actions.tsx
- apps/tangle-dapp/src/components/tables/Vaults/VaultsTable.tsx
- libs/ui-components/src/constants/index.ts
- Fix sorting issue on the vault table.
- Add link to faucet on the sidebar and account action.
- Closes https://github.com/tangle-network/dapp/issues/2889
> fix(tangle-dapp): Fix Sorting Issue & Add Faucet Link

- apps/leaderboard/CHANGELOG.md
- apps/leaderboard/package.json
- apps/tangle-cloud/CHANGELOG.md
- apps/tangle-cloud/package.json
- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
- libs/ui-components/CHANGELOG.md
- libs/ui-components/package.json
- release: tangle-cloud `v0.0.2`
- release: tangle-dapp `v0.1.3`
> [RELEASE] tangle-dapp v0.1.3 tangle-cloud v0.0.2

- apps/tangle-cloud/src/pages/operators/page.tsx
- apps/tangle-dapp/src/components/account/ProtocolStatisticCard/VaultsHightlightCard.tsx
- apps/tangle-dapp/src/features/claimCredits/components/ClaimCreditsButton.tsx
- apps/tangle-dapp/src/features/claimCredits/components/ClaimCreditsModal.tsx
- apps/tangle-dapp/src/features/claimCredits/components/CreditVelocityTooltip.tsx
- apps/tangle-dapp/src/utils/creditConstraints.ts
- libs/tangle-shared-ui/src/components/Restaking/JoinOperatorsModal.tsx
- libs/tangle-shared-ui/src/components/Restaking/OperatorsTableContainer.tsx
- libs/tangle-shared-ui/src/data/restake/useRestakeOperatorMap.ts
- added minimum credit claimable constraint and a tooltip component
- enchanced join operator UX (table update)
- minor UI improvements to vault statistics and tangle-cloud operators page
https://github.com/user-attachments/assets/15e6487f-795e-4abb-8404-d733d5b5ca88
> fix(tangle-cloud): Fixes & Improvements

- apps/tangle-dapp/CHANGELOG.md
- apps/tangle-dapp/package.json
> [RELEASE] tangle-dapp v0.1.5
